// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datastreams/MarketEvents.proto

package dalalstreet.api.datastreams;

import dalalstreet.api.models.MarketEvent;

/**
 * Protobuf type {@code proto.MarketEventUpdate}
 */
public  final class MarketEventUpdate extends
    com.google.protobuf.GeneratedMessageLite<
            MarketEventUpdate, MarketEventUpdate.Builder> implements
    // @@protoc_insertion_point(message_implements:proto.MarketEventUpdate)
        MarketEventUpdateOrBuilder {
  private MarketEventUpdate() {
  }
  public static final int MARKET_EVENT_FIELD_NUMBER = 1;
  private MarketEvent marketEvent_;
  /**
   * <code>optional .proto.MarketEvent market_event = 1;</code>
   */
  public boolean hasMarketEvent() {
    return marketEvent_ != null;
  }
  /**
   * <code>optional .proto.MarketEvent market_event = 1;</code>
   */
  public MarketEvent getMarketEvent() {
    return marketEvent_ == null ? MarketEvent.getDefaultInstance() : marketEvent_;
  }
  /**
   * <code>optional .proto.MarketEvent market_event = 1;</code>
   */
  private void setMarketEvent(MarketEvent value) {
    if (value == null) {
      throw new NullPointerException();
    }
    marketEvent_ = value;

    }
  /**
   * <code>optional .proto.MarketEvent market_event = 1;</code>
   */
  private void setMarketEvent(
      MarketEvent.Builder builderForValue) {
    marketEvent_ = builderForValue.build();

  }
  /**
   * <code>optional .proto.MarketEvent market_event = 1;</code>
   */
  private void mergeMarketEvent(MarketEvent value) {
    if (marketEvent_ != null &&
        marketEvent_ != MarketEvent.getDefaultInstance()) {
      marketEvent_ =
        MarketEvent.newBuilder(marketEvent_).mergeFrom(value).buildPartial();
    } else {
      marketEvent_ = value;
    }

  }
  /**
   * <code>optional .proto.MarketEvent market_event = 1;</code>
   */
  private void clearMarketEvent() {  marketEvent_ = null;

  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (marketEvent_ != null) {
      output.writeMessage(1, getMarketEvent());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (marketEvent_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getMarketEvent());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static MarketEventUpdate parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static MarketEventUpdate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static MarketEventUpdate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static MarketEventUpdate parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static MarketEventUpdate parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static MarketEventUpdate parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static MarketEventUpdate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static MarketEventUpdate parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static MarketEventUpdate parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static MarketEventUpdate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(MarketEventUpdate prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code proto.MarketEventUpdate}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
              MarketEventUpdate, Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.MarketEventUpdate)
          MarketEventUpdateOrBuilder {
    // Construct using dalalstreet.api.datastreams.MarketEventUpdate.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional .proto.MarketEvent market_event = 1;</code>
     */
    public boolean hasMarketEvent() {
      return instance.hasMarketEvent();
    }
    /**
     * <code>optional .proto.MarketEvent market_event = 1;</code>
     */
    public MarketEvent getMarketEvent() {
      return instance.getMarketEvent();
    }
    /**
     * <code>optional .proto.MarketEvent market_event = 1;</code>
     */
    public Builder setMarketEvent(MarketEvent value) {
      copyOnWrite();
      instance.setMarketEvent(value);
      return this;
      }
    /**
     * <code>optional .proto.MarketEvent market_event = 1;</code>
     */
    public Builder setMarketEvent(
        MarketEvent.Builder builderForValue) {
      copyOnWrite();
      instance.setMarketEvent(builderForValue);
      return this;
    }
    /**
     * <code>optional .proto.MarketEvent market_event = 1;</code>
     */
    public Builder mergeMarketEvent(MarketEvent value) {
      copyOnWrite();
      instance.mergeMarketEvent(value);
      return this;
    }
    /**
     * <code>optional .proto.MarketEvent market_event = 1;</code>
     */
    public Builder clearMarketEvent() {  copyOnWrite();
      instance.clearMarketEvent();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:proto.MarketEventUpdate)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new MarketEventUpdate();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        MarketEventUpdate other = (MarketEventUpdate) arg1;
        marketEvent_ = visitor.visitMessage(marketEvent_, other.marketEvent_);
        if (visitor == MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                MarketEvent.Builder subBuilder = null;
                if (marketEvent_ != null) {
                  subBuilder = marketEvent_.toBuilder();
                }
                marketEvent_ = input.readMessage(MarketEvent.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(marketEvent_);
                  marketEvent_ = subBuilder.buildPartial();
                }

                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (MarketEventUpdate.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:proto.MarketEventUpdate)
  private static final MarketEventUpdate DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new MarketEventUpdate();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static MarketEventUpdate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<MarketEventUpdate> PARSER;

  public static com.google.protobuf.Parser<MarketEventUpdate> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

