// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datastreams/MarketEvents.proto

package dalalstreet.api.datastreams;

import dalalstreet.api.models.MarketEvent;

public interface MarketEventUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.MarketEventUpdate)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .proto.MarketEvent market_event = 1;</code>
   */
  boolean hasMarketEvent();
  /**
   * <code>optional .proto.MarketEvent market_event = 1;</code>
   */
  MarketEvent getMarketEvent();
}
