// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datastreams/MyOrders.proto

package dalalstreet.api.datastreams;

/**
 * Protobuf type {@code proto.MyOrderUpdate}
 */
public  final class MyOrderUpdate extends
    com.google.protobuf.GeneratedMessageLite<
            MyOrderUpdate, MyOrderUpdate.Builder> implements
    // @@protoc_insertion_point(message_implements:proto.MyOrderUpdate)
        MyOrderUpdateOrBuilder {
  private MyOrderUpdate() {
  }
  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>optional uint32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }
  /**
   * <code>optional uint32 id = 1;</code>
   */
  private void setId(int value) {

    id_ = value;
  }
  /**
   * <code>optional uint32 id = 1;</code>
   */
  private void clearId() {

    id_ = 0;
  }

  public static final int IS_ASK_FIELD_NUMBER = 2;
  private boolean isAsk_;
  /**
   * <code>optional bool is_ask = 2;</code>
   */
  public boolean getIsAsk() {
    return isAsk_;
  }
  /**
   * <code>optional bool is_ask = 2;</code>
   */
  private void setIsAsk(boolean value) {

    isAsk_ = value;
  }
  /**
   * <code>optional bool is_ask = 2;</code>
   */
  private void clearIsAsk() {

    isAsk_ = false;
  }

  public static final int TRADE_QUANTITY_FIELD_NUMBER = 3;
  private int tradeQuantity_;
  /**
   * <code>optional uint32 trade_quantity = 3;</code>
   */
  public int getTradeQuantity() {
    return tradeQuantity_;
  }
  /**
   * <code>optional uint32 trade_quantity = 3;</code>
   */
  private void setTradeQuantity(int value) {

    tradeQuantity_ = value;
  }
  /**
   * <code>optional uint32 trade_quantity = 3;</code>
   */
  private void clearTradeQuantity() {

    tradeQuantity_ = 0;
  }

  public static final int IS_CLOSED_FIELD_NUMBER = 4;
  private boolean isClosed_;
  /**
   * <code>optional bool is_closed = 4;</code>
   */
  public boolean getIsClosed() {
    return isClosed_;
  }
  /**
   * <code>optional bool is_closed = 4;</code>
   */
  private void setIsClosed(boolean value) {

    isClosed_ = value;
  }
  /**
   * <code>optional bool is_closed = 4;</code>
   */
  private void clearIsClosed() {

    isClosed_ = false;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeUInt32(1, id_);
    }
    if (isAsk_ != false) {
      output.writeBool(2, isAsk_);
    }
    if (tradeQuantity_ != 0) {
      output.writeUInt32(3, tradeQuantity_);
    }
    if (isClosed_ != false) {
      output.writeBool(4, isClosed_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, id_);
    }
    if (isAsk_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, isAsk_);
    }
    if (tradeQuantity_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, tradeQuantity_);
    }
    if (isClosed_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, isClosed_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static MyOrderUpdate parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static MyOrderUpdate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static MyOrderUpdate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static MyOrderUpdate parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static MyOrderUpdate parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static MyOrderUpdate parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static MyOrderUpdate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static MyOrderUpdate parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static MyOrderUpdate parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static MyOrderUpdate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(MyOrderUpdate prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code proto.MyOrderUpdate}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
              MyOrderUpdate, Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.MyOrderUpdate)
          MyOrderUpdateOrBuilder {
    // Construct using dalalstreet.api.datastreams.MyOrderUpdate.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional uint32 id = 1;</code>
     */
    public int getId() {
      return instance.getId();
    }
    /**
     * <code>optional uint32 id = 1;</code>
     */
    public Builder setId(int value) {
      copyOnWrite();
      instance.setId(value);
      return this;
    }
    /**
     * <code>optional uint32 id = 1;</code>
     */
    public Builder clearId() {
      copyOnWrite();
      instance.clearId();
      return this;
    }

    /**
     * <code>optional bool is_ask = 2;</code>
     */
    public boolean getIsAsk() {
      return instance.getIsAsk();
    }
    /**
     * <code>optional bool is_ask = 2;</code>
     */
    public Builder setIsAsk(boolean value) {
      copyOnWrite();
      instance.setIsAsk(value);
      return this;
    }
    /**
     * <code>optional bool is_ask = 2;</code>
     */
    public Builder clearIsAsk() {
      copyOnWrite();
      instance.clearIsAsk();
      return this;
    }

    /**
     * <code>optional uint32 trade_quantity = 3;</code>
     */
    public int getTradeQuantity() {
      return instance.getTradeQuantity();
    }
    /**
     * <code>optional uint32 trade_quantity = 3;</code>
     */
    public Builder setTradeQuantity(int value) {
      copyOnWrite();
      instance.setTradeQuantity(value);
      return this;
    }
    /**
     * <code>optional uint32 trade_quantity = 3;</code>
     */
    public Builder clearTradeQuantity() {
      copyOnWrite();
      instance.clearTradeQuantity();
      return this;
    }

    /**
     * <code>optional bool is_closed = 4;</code>
     */
    public boolean getIsClosed() {
      return instance.getIsClosed();
    }
    /**
     * <code>optional bool is_closed = 4;</code>
     */
    public Builder setIsClosed(boolean value) {
      copyOnWrite();
      instance.setIsClosed(value);
      return this;
    }
    /**
     * <code>optional bool is_closed = 4;</code>
     */
    public Builder clearIsClosed() {
      copyOnWrite();
      instance.clearIsClosed();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:proto.MyOrderUpdate)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new MyOrderUpdate();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        MyOrderUpdate other = (MyOrderUpdate) arg1;
        id_ = visitor.visitInt(id_ != 0, id_,
            other.id_ != 0, other.id_);
        isAsk_ = visitor.visitBoolean(isAsk_ != false, isAsk_,
            other.isAsk_ != false, other.isAsk_);
        tradeQuantity_ = visitor.visitInt(tradeQuantity_ != 0, tradeQuantity_,
            other.tradeQuantity_ != 0, other.tradeQuantity_);
        isClosed_ = visitor.visitBoolean(isClosed_ != false, isClosed_,
            other.isClosed_ != false, other.isClosed_);
        if (visitor == MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                id_ = input.readUInt32();
                break;
              }
              case 16: {

                isAsk_ = input.readBool();
                break;
              }
              case 24: {

                tradeQuantity_ = input.readUInt32();
                break;
              }
              case 32: {

                isClosed_ = input.readBool();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (MyOrderUpdate.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:proto.MyOrderUpdate)
  private static final MyOrderUpdate DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new MyOrderUpdate();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static MyOrderUpdate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<MyOrderUpdate> PARSER;

  public static com.google.protobuf.Parser<MyOrderUpdate> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

