// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datastreams/MyOrders.proto

package dalalstreet.api.datastreams;

public final class MyOrders {
  private MyOrders() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
