// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datastreams/Notifications.proto

package dalalstreet.api.datastreams;

public final class Notifications {
  private Notifications() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
