// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datastreams/Notifications.proto

package dalalstreet.api.datastreams;

import dalalstreet.api.models.Notification;

public interface NotificationUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.NotificationUpdate)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .proto.Notification notification = 1;</code>
   */
  boolean hasNotification();
  /**
   * <code>optional .proto.Notification notification = 1;</code>
   */
  Notification getNotification();
}
