// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datastreams/StockPrices.proto

package dalalstreet.api.datastreams;

public interface StockPricesUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.StockPricesUpdate)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * key: stockId, value: price
   * </pre>
   *
   * <code>map&lt;uint32, uint32&gt; prices = 1;</code>
   */
  int getPricesCount();
  /**
   * <pre>
   * key: stockId, value: price
   * </pre>
   *
   * <code>map&lt;uint32, uint32&gt; prices = 1;</code>
   */
  boolean containsPrices(
          int key);
  /**
   * Use {@link #getPricesMap()} instead.
   */
  @Deprecated
  java.util.Map<Integer, Integer>
  getPrices();
  /**
   * <pre>
   * key: stockId, value: price
   * </pre>
   *
   * <code>map&lt;uint32, uint32&gt; prices = 1;</code>
   */
  java.util.Map<Integer, Integer>
  getPricesMap();
  /**
   * <pre>
   * key: stockId, value: price
   * </pre>
   *
   * <code>map&lt;uint32, uint32&gt; prices = 1;</code>
   */

  int getPricesOrDefault(
          int key,
          int defaultValue);
  /**
   * <pre>
   * key: stockId, value: price
   * </pre>
   *
   * <code>map&lt;uint32, uint32&gt; prices = 1;</code>
   */

  int getPricesOrThrow(
          int key);
}
