// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datastreams/Subscribe.proto

package dalalstreet.api.datastreams;

public interface SubscribeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.SubscribeResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .proto.SubscribeResponse.StatusCode status_code = 1;</code>
   */
  int getStatusCodeValue();
  /**
   * <code>optional .proto.SubscribeResponse.StatusCode status_code = 1;</code>
   */
  SubscribeResponse.StatusCode getStatusCode();

  /**
   * <code>optional string status_message = 2;</code>
   */
  String getStatusMessage();
  /**
   * <code>optional string status_message = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusMessageBytes();

  /**
   * <pre>
   * To be used for unsubscribing and for fetching the data.
   * </pre>
   *
   * <code>optional .proto.SubscriptionId subscription_id = 3;</code>
   */
  boolean hasSubscriptionId();
  /**
   * <pre>
   * To be used for unsubscribing and for fetching the data.
   * </pre>
   *
   * <code>optional .proto.SubscriptionId subscription_id = 3;</code>
   */
  SubscriptionId getSubscriptionId();
}
