// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datastreams/Subscribe.proto

package dalalstreet.api.datastreams;

/**
 * Protobuf type {@code proto.SubscribeRequest}
 */
public  final class SubscribeRequest extends
    com.google.protobuf.GeneratedMessageLite<
            SubscribeRequest, SubscribeRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:proto.SubscribeRequest)
        SubscribeRequestOrBuilder {
  private SubscribeRequest() {
    dataStreamId_ = "";
  }
  public static final int DATA_STREAM_TYPE_FIELD_NUMBER = 1;
  private int dataStreamType_;
  /**
   * <code>optional .proto.DataStreamType data_stream_type = 1;</code>
   */
  public int getDataStreamTypeValue() {
    return dataStreamType_;
  }
  /**
   * <code>optional .proto.DataStreamType data_stream_type = 1;</code>
   */
  public DataStreamType getDataStreamType() {
    DataStreamType result = DataStreamType.forNumber(dataStreamType_);
    return result == null ? DataStreamType.UNRECOGNIZED : result;
  }
  /**
   * <code>optional .proto.DataStreamType data_stream_type = 1;</code>
   */
  private void setDataStreamTypeValue(int value) {
      dataStreamType_ = value;
  }
  /**
   * <code>optional .proto.DataStreamType data_stream_type = 1;</code>
   */
  private void setDataStreamType(DataStreamType value) {
    if (value == null) {
      throw new NullPointerException();
    }

    dataStreamType_ = value.getNumber();
  }
  /**
   * <code>optional .proto.DataStreamType data_stream_type = 1;</code>
   */
  private void clearDataStreamType() {

    dataStreamType_ = 0;
  }

  public static final int DATA_STREAM_ID_FIELD_NUMBER = 2;
  private String dataStreamId_;
  /**
   * <pre>
   * useful for MARKET_DEPTH &amp; maybe some others
   * </pre>
   *
   * <code>optional string data_stream_id = 2;</code>
   */
  public String getDataStreamId() {
    return dataStreamId_;
  }
  /**
   * <pre>
   * useful for MARKET_DEPTH &amp; maybe some others
   * </pre>
   *
   * <code>optional string data_stream_id = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDataStreamIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(dataStreamId_);
  }
  /**
   * <pre>
   * useful for MARKET_DEPTH &amp; maybe some others
   * </pre>
   *
   * <code>optional string data_stream_id = 2;</code>
   */
  private void setDataStreamId(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }

    dataStreamId_ = value;
  }
  /**
   * <pre>
   * useful for MARKET_DEPTH &amp; maybe some others
   * </pre>
   *
   * <code>optional string data_stream_id = 2;</code>
   */
  private void clearDataStreamId() {

    dataStreamId_ = getDefaultInstance().getDataStreamId();
  }
  /**
   * <pre>
   * useful for MARKET_DEPTH &amp; maybe some others
   * </pre>
   *
   * <code>optional string data_stream_id = 2;</code>
   */
  private void setDataStreamIdBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

    dataStreamId_ = value.toStringUtf8();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (dataStreamType_ != DataStreamType.MARKET_DEPTH.getNumber()) {
      output.writeEnum(1, dataStreamType_);
    }
    if (!dataStreamId_.isEmpty()) {
      output.writeString(2, getDataStreamId());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (dataStreamType_ != DataStreamType.MARKET_DEPTH.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, dataStreamType_);
    }
    if (!dataStreamId_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(2, getDataStreamId());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static SubscribeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static SubscribeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static SubscribeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static SubscribeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static SubscribeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static SubscribeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static SubscribeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static SubscribeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static SubscribeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static SubscribeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(SubscribeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code proto.SubscribeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
              SubscribeRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.SubscribeRequest)
          SubscribeRequestOrBuilder {
    // Construct using dalalstreet.api.datastreams.SubscribeRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional .proto.DataStreamType data_stream_type = 1;</code>
     */
    public int getDataStreamTypeValue() {
      return instance.getDataStreamTypeValue();
    }
    /**
     * <code>optional .proto.DataStreamType data_stream_type = 1;</code>
     */
    public Builder setDataStreamTypeValue(int value) {
      copyOnWrite();
      instance.setDataStreamTypeValue(value);
      return this;
    }
    /**
     * <code>optional .proto.DataStreamType data_stream_type = 1;</code>
     */
    public DataStreamType getDataStreamType() {
      return instance.getDataStreamType();
    }
    /**
     * <code>optional .proto.DataStreamType data_stream_type = 1;</code>
     */
    public Builder setDataStreamType(DataStreamType value) {
      copyOnWrite();
      instance.setDataStreamType(value);
      return this;
    }
    /**
     * <code>optional .proto.DataStreamType data_stream_type = 1;</code>
     */
    public Builder clearDataStreamType() {
      copyOnWrite();
      instance.clearDataStreamType();
      return this;
    }

    /**
     * <pre>
     * useful for MARKET_DEPTH &amp; maybe some others
     * </pre>
     *
     * <code>optional string data_stream_id = 2;</code>
     */
    public String getDataStreamId() {
      return instance.getDataStreamId();
    }
    /**
     * <pre>
     * useful for MARKET_DEPTH &amp; maybe some others
     * </pre>
     *
     * <code>optional string data_stream_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDataStreamIdBytes() {
      return instance.getDataStreamIdBytes();
    }
    /**
     * <pre>
     * useful for MARKET_DEPTH &amp; maybe some others
     * </pre>
     *
     * <code>optional string data_stream_id = 2;</code>
     */
    public Builder setDataStreamId(
        String value) {
      copyOnWrite();
      instance.setDataStreamId(value);
      return this;
    }
    /**
     * <pre>
     * useful for MARKET_DEPTH &amp; maybe some others
     * </pre>
     *
     * <code>optional string data_stream_id = 2;</code>
     */
    public Builder clearDataStreamId() {
      copyOnWrite();
      instance.clearDataStreamId();
      return this;
    }
    /**
     * <pre>
     * useful for MARKET_DEPTH &amp; maybe some others
     * </pre>
     *
     * <code>optional string data_stream_id = 2;</code>
     */
    public Builder setDataStreamIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDataStreamIdBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:proto.SubscribeRequest)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new SubscribeRequest();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        SubscribeRequest other = (SubscribeRequest) arg1;
        dataStreamType_ = visitor.visitInt(dataStreamType_ != 0, dataStreamType_,    other.dataStreamType_ != 0, other.dataStreamType_);
        dataStreamId_ = visitor.visitString(!dataStreamId_.isEmpty(), dataStreamId_,
            !other.dataStreamId_.isEmpty(), other.dataStreamId_);
        if (visitor == MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();

                dataStreamType_ = rawValue;
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                dataStreamId_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (SubscribeRequest.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:proto.SubscribeRequest)
  private static final SubscribeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SubscribeRequest();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static SubscribeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<SubscribeRequest> PARSER;

  public static com.google.protobuf.Parser<SubscribeRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

