// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datastreams/MarketDepth.proto

package dalalstreet.api.datastreams;

public interface TradeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Trade)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional uint32 trade_price = 1;</code>
   */
  int getTradePrice();

  /**
   * <code>optional uint32 trade_quantity = 2;</code>
   */
  int getTradeQuantity();

  /**
   * <code>optional string trade_time = 3;</code>
   */
  String getTradeTime();
  /**
   * <code>optional string trade_time = 3;</code>
   */
  com.google.protobuf.ByteString
      getTradeTimeBytes();
}
