// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datastreams/Transactions.proto

package dalalstreet.api.datastreams;

import dalalstreet.api.models.Transaction;

public interface TransactionUpdateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.TransactionUpdate)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .proto.Transaction transaction = 1;</code>
   */
  boolean hasTransaction();
  /**
   * <code>optional .proto.Transaction transaction = 1;</code>
   */
  Transaction getTransaction();
}
