// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datastreams/Transactions.proto

package dalalstreet.api.datastreams;

public final class Transactions {
  private Transactions() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
