// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datastreams/Subscribe.proto

package dalalstreet.api.datastreams;

/**
 * Protobuf type {@code proto.UnsubscribeRequest}
 */
public  final class UnsubscribeRequest extends
    com.google.protobuf.GeneratedMessageLite<
            UnsubscribeRequest, UnsubscribeRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:proto.UnsubscribeRequest)
        UnsubscribeRequestOrBuilder {
  private UnsubscribeRequest() {
  }
  public static final int SUBSCRIPTION_ID_FIELD_NUMBER = 1;
  private SubscriptionId subscriptionId_;
  /**
   * <code>optional .proto.SubscriptionId subscription_id = 1;</code>
   */
  public boolean hasSubscriptionId() {
    return subscriptionId_ != null;
  }
  /**
   * <code>optional .proto.SubscriptionId subscription_id = 1;</code>
   */
  public SubscriptionId getSubscriptionId() {
    return subscriptionId_ == null ? SubscriptionId.getDefaultInstance() : subscriptionId_;
  }
  /**
   * <code>optional .proto.SubscriptionId subscription_id = 1;</code>
   */
  private void setSubscriptionId(SubscriptionId value) {
    if (value == null) {
      throw new NullPointerException();
    }
    subscriptionId_ = value;

    }
  /**
   * <code>optional .proto.SubscriptionId subscription_id = 1;</code>
   */
  private void setSubscriptionId(
      SubscriptionId.Builder builderForValue) {
    subscriptionId_ = builderForValue.build();

  }
  /**
   * <code>optional .proto.SubscriptionId subscription_id = 1;</code>
   */
  private void mergeSubscriptionId(SubscriptionId value) {
    if (subscriptionId_ != null &&
        subscriptionId_ != SubscriptionId.getDefaultInstance()) {
      subscriptionId_ =
        SubscriptionId.newBuilder(subscriptionId_).mergeFrom(value).buildPartial();
    } else {
      subscriptionId_ = value;
    }

  }
  /**
   * <code>optional .proto.SubscriptionId subscription_id = 1;</code>
   */
  private void clearSubscriptionId() {  subscriptionId_ = null;

  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (subscriptionId_ != null) {
      output.writeMessage(1, getSubscriptionId());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (subscriptionId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSubscriptionId());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static UnsubscribeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static UnsubscribeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static UnsubscribeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static UnsubscribeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static UnsubscribeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static UnsubscribeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static UnsubscribeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static UnsubscribeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static UnsubscribeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static UnsubscribeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(UnsubscribeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code proto.UnsubscribeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
              UnsubscribeRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.UnsubscribeRequest)
          UnsubscribeRequestOrBuilder {
    // Construct using dalalstreet.api.datastreams.UnsubscribeRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional .proto.SubscriptionId subscription_id = 1;</code>
     */
    public boolean hasSubscriptionId() {
      return instance.hasSubscriptionId();
    }
    /**
     * <code>optional .proto.SubscriptionId subscription_id = 1;</code>
     */
    public SubscriptionId getSubscriptionId() {
      return instance.getSubscriptionId();
    }
    /**
     * <code>optional .proto.SubscriptionId subscription_id = 1;</code>
     */
    public Builder setSubscriptionId(SubscriptionId value) {
      copyOnWrite();
      instance.setSubscriptionId(value);
      return this;
      }
    /**
     * <code>optional .proto.SubscriptionId subscription_id = 1;</code>
     */
    public Builder setSubscriptionId(
        SubscriptionId.Builder builderForValue) {
      copyOnWrite();
      instance.setSubscriptionId(builderForValue);
      return this;
    }
    /**
     * <code>optional .proto.SubscriptionId subscription_id = 1;</code>
     */
    public Builder mergeSubscriptionId(SubscriptionId value) {
      copyOnWrite();
      instance.mergeSubscriptionId(value);
      return this;
    }
    /**
     * <code>optional .proto.SubscriptionId subscription_id = 1;</code>
     */
    public Builder clearSubscriptionId() {  copyOnWrite();
      instance.clearSubscriptionId();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:proto.UnsubscribeRequest)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new UnsubscribeRequest();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        UnsubscribeRequest other = (UnsubscribeRequest) arg1;
        subscriptionId_ = visitor.visitMessage(subscriptionId_, other.subscriptionId_);
        if (visitor == MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                SubscriptionId.Builder subBuilder = null;
                if (subscriptionId_ != null) {
                  subBuilder = subscriptionId_.toBuilder();
                }
                subscriptionId_ = input.readMessage(SubscriptionId.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(subscriptionId_);
                  subscriptionId_ = subBuilder.buildPartial();
                }

                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (UnsubscribeRequest.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:proto.UnsubscribeRequest)
  private static final UnsubscribeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new UnsubscribeRequest();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static UnsubscribeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<UnsubscribeRequest> PARSER;

  public static com.google.protobuf.Parser<UnsubscribeRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

