// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datastreams/Subscribe.proto

package dalalstreet.api.datastreams;

public interface UnsubscribeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.UnsubscribeRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .proto.SubscriptionId subscription_id = 1;</code>
   */
  boolean hasSubscriptionId();
  /**
   * <code>optional .proto.SubscriptionId subscription_id = 1;</code>
   */
  SubscriptionId getSubscriptionId();
}
