// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datastreams/Subscribe.proto

package dalalstreet.api.datastreams;

public interface UnsubscribeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.UnsubscribeResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .proto.UnsubscribeResponse.StatusCode status_code = 1;</code>
   */
  int getStatusCodeValue();
  /**
   * <code>optional .proto.UnsubscribeResponse.StatusCode status_code = 1;</code>
   */
  UnsubscribeResponse.StatusCode getStatusCode();

  /**
   * <code>optional string status_message = 2;</code>
   */
  String getStatusMessage();
  /**
   * <code>optional string status_message = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusMessageBytes();
}
