// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DalalMessage.proto

package dalalstreet.api;

public final class DalalMessage {
  private DalalMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
