// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: models/MarketEvent.proto

package dalalstreet.api.models;

public interface MarketEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.MarketEvent)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional uint32 id = 1;</code>
   */
  int getId();

  /**
   * <code>optional uint32 stock_id = 2;</code>
   */
  int getStockId();

  /**
   * <code>optional string headline = 3;</code>
   */
  String getHeadline();
  /**
   * <code>optional string headline = 3;</code>
   */
  com.google.protobuf.ByteString
      getHeadlineBytes();

  /**
   * <code>optional string text = 4;</code>
   */
  String getText();
  /**
   * <code>optional string text = 4;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>optional sint32 emotion_score = 5;</code>
   */
  int getEmotionScore();

  /**
   * <code>optional bool is_global = 7;</code>
   */
  boolean getIsGlobal();

  /**
   * <code>optional string created_at = 6;</code>
   */
  String getCreatedAt();
  /**
   * <code>optional string created_at = 6;</code>
   */
  com.google.protobuf.ByteString
      getCreatedAtBytes();
}
