// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: models/MarketEvent.proto

package dalalstreet.api.models;

public final class MarketEventOuterClass {
  private MarketEventOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
