// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: models/MortgageDetail.proto

package dalalstreet.api.models;

public interface MortgageDetailOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.MortgageDetail)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional uint32 id = 1;</code>
   */
  int getId();

  /**
   * <code>optional uint32 user_id = 2;</code>
   */
  int getUserId();

  /**
   * <code>optional uint32 stock_id = 3;</code>
   */
  int getStockId();

  /**
   * <code>optional uint32 stocks_in_bank = 4;</code>
   */
  int getStocksInBank();
}
