// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: models/Notification.proto

package dalalstreet.api.models;

/**
 * Protobuf type {@code proto.Notification}
 */
public  final class Notification extends
    com.google.protobuf.GeneratedMessageLite<
            Notification, Notification.Builder> implements
    // @@protoc_insertion_point(message_implements:proto.Notification)
        NotificationOrBuilder {
  private Notification() {
    text_ = "";
    createdAt_ = "";
  }
  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>optional uint32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }
  /**
   * <code>optional uint32 id = 1;</code>
   */
  private void setId(int value) {

    id_ = value;
  }
  /**
   * <code>optional uint32 id = 1;</code>
   */
  private void clearId() {

    id_ = 0;
  }

  public static final int USER_ID_FIELD_NUMBER = 2;
  private int userId_;
  /**
   * <code>optional uint32 user_id = 2;</code>
   */
  public int getUserId() {
    return userId_;
  }
  /**
   * <code>optional uint32 user_id = 2;</code>
   */
  private void setUserId(int value) {

    userId_ = value;
  }
  /**
   * <code>optional uint32 user_id = 2;</code>
   */
  private void clearUserId() {

    userId_ = 0;
  }

  public static final int TEXT_FIELD_NUMBER = 3;
  private String text_;
  /**
   * <code>optional string text = 3;</code>
   */
  public String getText() {
    return text_;
  }
  /**
   * <code>optional string text = 3;</code>
   */
  public com.google.protobuf.ByteString
      getTextBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(text_);
  }
  /**
   * <code>optional string text = 3;</code>
   */
  private void setText(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }

    text_ = value;
  }
  /**
   * <code>optional string text = 3;</code>
   */
  private void clearText() {

    text_ = getDefaultInstance().getText();
  }
  /**
   * <code>optional string text = 3;</code>
   */
  private void setTextBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

    text_ = value.toStringUtf8();
  }

  public static final int IS_BROADCAST_FIELD_NUMBER = 5;
  private boolean isBroadcast_;
  /**
   * <code>optional bool is_broadcast = 5;</code>
   */
  public boolean getIsBroadcast() {
    return isBroadcast_;
  }
  /**
   * <code>optional bool is_broadcast = 5;</code>
   */
  private void setIsBroadcast(boolean value) {

    isBroadcast_ = value;
  }
  /**
   * <code>optional bool is_broadcast = 5;</code>
   */
  private void clearIsBroadcast() {

    isBroadcast_ = false;
  }

  public static final int CREATED_AT_FIELD_NUMBER = 4;
  private String createdAt_;
  /**
   * <code>optional string created_at = 4;</code>
   */
  public String getCreatedAt() {
    return createdAt_;
  }
  /**
   * <code>optional string created_at = 4;</code>
   */
  public com.google.protobuf.ByteString
      getCreatedAtBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(createdAt_);
  }
  /**
   * <code>optional string created_at = 4;</code>
   */
  private void setCreatedAt(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }

    createdAt_ = value;
  }
  /**
   * <code>optional string created_at = 4;</code>
   */
  private void clearCreatedAt() {

    createdAt_ = getDefaultInstance().getCreatedAt();
  }
  /**
   * <code>optional string created_at = 4;</code>
   */
  private void setCreatedAtBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

    createdAt_ = value.toStringUtf8();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeUInt32(1, id_);
    }
    if (userId_ != 0) {
      output.writeUInt32(2, userId_);
    }
    if (!text_.isEmpty()) {
      output.writeString(3, getText());
    }
    if (!createdAt_.isEmpty()) {
      output.writeString(4, getCreatedAt());
    }
    if (isBroadcast_ != false) {
      output.writeBool(5, isBroadcast_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, id_);
    }
    if (userId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, userId_);
    }
    if (!text_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(3, getText());
    }
    if (!createdAt_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(4, getCreatedAt());
    }
    if (isBroadcast_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, isBroadcast_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static Notification parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static Notification parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static Notification parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static Notification parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static Notification parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static Notification parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static Notification parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static Notification parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static Notification parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static Notification parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Notification prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code proto.Notification}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
              Notification, Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.Notification)
          NotificationOrBuilder {
    // Construct using dalalstreet.api.models.Notification.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional uint32 id = 1;</code>
     */
    public int getId() {
      return instance.getId();
    }
    /**
     * <code>optional uint32 id = 1;</code>
     */
    public Builder setId(int value) {
      copyOnWrite();
      instance.setId(value);
      return this;
    }
    /**
     * <code>optional uint32 id = 1;</code>
     */
    public Builder clearId() {
      copyOnWrite();
      instance.clearId();
      return this;
    }

    /**
     * <code>optional uint32 user_id = 2;</code>
     */
    public int getUserId() {
      return instance.getUserId();
    }
    /**
     * <code>optional uint32 user_id = 2;</code>
     */
    public Builder setUserId(int value) {
      copyOnWrite();
      instance.setUserId(value);
      return this;
    }
    /**
     * <code>optional uint32 user_id = 2;</code>
     */
    public Builder clearUserId() {
      copyOnWrite();
      instance.clearUserId();
      return this;
    }

    /**
     * <code>optional string text = 3;</code>
     */
    public String getText() {
      return instance.getText();
    }
    /**
     * <code>optional string text = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      return instance.getTextBytes();
    }
    /**
     * <code>optional string text = 3;</code>
     */
    public Builder setText(
        String value) {
      copyOnWrite();
      instance.setText(value);
      return this;
    }
    /**
     * <code>optional string text = 3;</code>
     */
    public Builder clearText() {
      copyOnWrite();
      instance.clearText();
      return this;
    }
    /**
     * <code>optional string text = 3;</code>
     */
    public Builder setTextBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTextBytes(value);
      return this;
    }

    /**
     * <code>optional bool is_broadcast = 5;</code>
     */
    public boolean getIsBroadcast() {
      return instance.getIsBroadcast();
    }
    /**
     * <code>optional bool is_broadcast = 5;</code>
     */
    public Builder setIsBroadcast(boolean value) {
      copyOnWrite();
      instance.setIsBroadcast(value);
      return this;
    }
    /**
     * <code>optional bool is_broadcast = 5;</code>
     */
    public Builder clearIsBroadcast() {
      copyOnWrite();
      instance.clearIsBroadcast();
      return this;
    }

    /**
     * <code>optional string created_at = 4;</code>
     */
    public String getCreatedAt() {
      return instance.getCreatedAt();
    }
    /**
     * <code>optional string created_at = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCreatedAtBytes() {
      return instance.getCreatedAtBytes();
    }
    /**
     * <code>optional string created_at = 4;</code>
     */
    public Builder setCreatedAt(
        String value) {
      copyOnWrite();
      instance.setCreatedAt(value);
      return this;
    }
    /**
     * <code>optional string created_at = 4;</code>
     */
    public Builder clearCreatedAt() {
      copyOnWrite();
      instance.clearCreatedAt();
      return this;
    }
    /**
     * <code>optional string created_at = 4;</code>
     */
    public Builder setCreatedAtBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setCreatedAtBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:proto.Notification)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new Notification();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        Notification other = (Notification) arg1;
        id_ = visitor.visitInt(id_ != 0, id_,
            other.id_ != 0, other.id_);
        userId_ = visitor.visitInt(userId_ != 0, userId_,
            other.userId_ != 0, other.userId_);
        text_ = visitor.visitString(!text_.isEmpty(), text_,
            !other.text_.isEmpty(), other.text_);
        isBroadcast_ = visitor.visitBoolean(isBroadcast_ != false, isBroadcast_,
            other.isBroadcast_ != false, other.isBroadcast_);
        createdAt_ = visitor.visitString(!createdAt_.isEmpty(), createdAt_,
            !other.createdAt_.isEmpty(), other.createdAt_);
        if (visitor == MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                id_ = input.readUInt32();
                break;
              }
              case 16: {

                userId_ = input.readUInt32();
                break;
              }
              case 26: {
                String s = input.readStringRequireUtf8();

                text_ = s;
                break;
              }
              case 34: {
                String s = input.readStringRequireUtf8();

                createdAt_ = s;
                break;
              }
              case 40: {

                isBroadcast_ = input.readBool();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (Notification.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:proto.Notification)
  private static final Notification DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Notification();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static Notification getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Notification> PARSER;

  public static com.google.protobuf.Parser<Notification> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

