// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: models/OrderFill.proto

package dalalstreet.api.models;

public interface OrderFillOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.OrderFill)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional uint32 transaction_id = 1;</code>
   */
  int getTransactionId();

  /**
   * <code>optional uint32 bid_id = 2;</code>
   */
  int getBidId();

  /**
   * <code>optional uint32 ask_id = 3;</code>
   */
  int getAskId();
}
