// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: models/OrderType.proto

package dalalstreet.api.models;

/**
 * Protobuf enum {@code proto.OrderType}
 */
public enum OrderType
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>LIMIT = 0;</code>
   */
  LIMIT(0),
  /**
   * <code>MARKET = 1;</code>
   */
  MARKET(1),
  /**
   * <code>STOPLOSS = 2;</code>
   */
  STOPLOSS(2),
  /**
   * <code>STOPLOSSACTIVE = 3;</code>
   */
  STOPLOSSACTIVE(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>LIMIT = 0;</code>
   */
  public static final int LIMIT_VALUE = 0;
  /**
   * <code>MARKET = 1;</code>
   */
  public static final int MARKET_VALUE = 1;
  /**
   * <code>STOPLOSS = 2;</code>
   */
  public static final int STOPLOSS_VALUE = 2;
  /**
   * <code>STOPLOSSACTIVE = 3;</code>
   */
  public static final int STOPLOSSACTIVE_VALUE = 3;


  public final int getNumber() {
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static OrderType valueOf(int value) {
    return forNumber(value);
  }

  public static OrderType forNumber(int value) {
    switch (value) {
      case 0: return LIMIT;
      case 1: return MARKET;
      case 2: return STOPLOSS;
      case 3: return STOPLOSSACTIVE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<OrderType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
          OrderType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<OrderType>() {
          public OrderType findValueByNumber(int number) {
            return OrderType.forNumber(number);
          }
        };

  private final int value;

  private OrderType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:proto.OrderType)
}

