// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: models/OrderType.proto

package dalalstreet.api.models;

public final class OrderTypeOuterClass {
  private OrderTypeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
