// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: models/OrderFill.proto

package dalalstreet.api.models;

public final class OrderFillOuterClass {
  private OrderFillOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
