// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: models/OrderFill.proto

package dalalstreet.api.models;

/**
 * Protobuf type {@code proto.OrderFill}
 */
public  final class OrderFill extends
    com.google.protobuf.GeneratedMessageLite<
            OrderFill, OrderFill.Builder> implements
    // @@protoc_insertion_point(message_implements:proto.OrderFill)
        OrderFillOrBuilder {
  private OrderFill() {
  }
  public static final int TRANSACTION_ID_FIELD_NUMBER = 1;
  private int transactionId_;
  /**
   * <code>optional uint32 transaction_id = 1;</code>
   */
  public int getTransactionId() {
    return transactionId_;
  }
  /**
   * <code>optional uint32 transaction_id = 1;</code>
   */
  private void setTransactionId(int value) {

    transactionId_ = value;
  }
  /**
   * <code>optional uint32 transaction_id = 1;</code>
   */
  private void clearTransactionId() {

    transactionId_ = 0;
  }

  public static final int BID_ID_FIELD_NUMBER = 2;
  private int bidId_;
  /**
   * <code>optional uint32 bid_id = 2;</code>
   */
  public int getBidId() {
    return bidId_;
  }
  /**
   * <code>optional uint32 bid_id = 2;</code>
   */
  private void setBidId(int value) {

    bidId_ = value;
  }
  /**
   * <code>optional uint32 bid_id = 2;</code>
   */
  private void clearBidId() {

    bidId_ = 0;
  }

  public static final int ASK_ID_FIELD_NUMBER = 3;
  private int askId_;
  /**
   * <code>optional uint32 ask_id = 3;</code>
   */
  public int getAskId() {
    return askId_;
  }
  /**
   * <code>optional uint32 ask_id = 3;</code>
   */
  private void setAskId(int value) {

    askId_ = value;
  }
  /**
   * <code>optional uint32 ask_id = 3;</code>
   */
  private void clearAskId() {

    askId_ = 0;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (transactionId_ != 0) {
      output.writeUInt32(1, transactionId_);
    }
    if (bidId_ != 0) {
      output.writeUInt32(2, bidId_);
    }
    if (askId_ != 0) {
      output.writeUInt32(3, askId_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (transactionId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, transactionId_);
    }
    if (bidId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, bidId_);
    }
    if (askId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, askId_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static OrderFill parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static OrderFill parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static OrderFill parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static OrderFill parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static OrderFill parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static OrderFill parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static OrderFill parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static OrderFill parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static OrderFill parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static OrderFill parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(OrderFill prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code proto.OrderFill}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
              OrderFill, Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.OrderFill)
          OrderFillOrBuilder {
    // Construct using dalalstreet.api.models.OrderFill.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional uint32 transaction_id = 1;</code>
     */
    public int getTransactionId() {
      return instance.getTransactionId();
    }
    /**
     * <code>optional uint32 transaction_id = 1;</code>
     */
    public Builder setTransactionId(int value) {
      copyOnWrite();
      instance.setTransactionId(value);
      return this;
    }
    /**
     * <code>optional uint32 transaction_id = 1;</code>
     */
    public Builder clearTransactionId() {
      copyOnWrite();
      instance.clearTransactionId();
      return this;
    }

    /**
     * <code>optional uint32 bid_id = 2;</code>
     */
    public int getBidId() {
      return instance.getBidId();
    }
    /**
     * <code>optional uint32 bid_id = 2;</code>
     */
    public Builder setBidId(int value) {
      copyOnWrite();
      instance.setBidId(value);
      return this;
    }
    /**
     * <code>optional uint32 bid_id = 2;</code>
     */
    public Builder clearBidId() {
      copyOnWrite();
      instance.clearBidId();
      return this;
    }

    /**
     * <code>optional uint32 ask_id = 3;</code>
     */
    public int getAskId() {
      return instance.getAskId();
    }
    /**
     * <code>optional uint32 ask_id = 3;</code>
     */
    public Builder setAskId(int value) {
      copyOnWrite();
      instance.setAskId(value);
      return this;
    }
    /**
     * <code>optional uint32 ask_id = 3;</code>
     */
    public Builder clearAskId() {
      copyOnWrite();
      instance.clearAskId();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:proto.OrderFill)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new OrderFill();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        OrderFill other = (OrderFill) arg1;
        transactionId_ = visitor.visitInt(transactionId_ != 0, transactionId_,
            other.transactionId_ != 0, other.transactionId_);
        bidId_ = visitor.visitInt(bidId_ != 0, bidId_,
            other.bidId_ != 0, other.bidId_);
        askId_ = visitor.visitInt(askId_ != 0, askId_,
            other.askId_ != 0, other.askId_);
        if (visitor == MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                transactionId_ = input.readUInt32();
                break;
              }
              case 16: {

                bidId_ = input.readUInt32();
                break;
              }
              case 24: {

                askId_ = input.readUInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (OrderFill.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:proto.OrderFill)
  private static final OrderFill DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new OrderFill();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static OrderFill getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<OrderFill> PARSER;

  public static com.google.protobuf.Parser<OrderFill> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

