// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: models/Stock.proto

package dalalstreet.api.models;

public interface StockOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Stock)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional uint32 id = 1;</code>
   */
  int getId();

  /**
   * <code>optional string short_name = 2;</code>
   */
  String getShortName();
  /**
   * <code>optional string short_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getShortNameBytes();

  /**
   * <code>optional string full_name = 3;</code>
   */
  String getFullName();
  /**
   * <code>optional string full_name = 3;</code>
   */
  com.google.protobuf.ByteString
      getFullNameBytes();

  /**
   * <code>optional string description = 4;</code>
   */
  String getDescription();
  /**
   * <code>optional string description = 4;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>optional uint32 current_price = 5;</code>
   */
  int getCurrentPrice();

  /**
   * <code>optional uint32 day_high = 6;</code>
   */
  int getDayHigh();

  /**
   * <code>optional uint32 day_low = 7;</code>
   */
  int getDayLow();

  /**
   * <code>optional uint32 all_time_high = 8;</code>
   */
  int getAllTimeHigh();

  /**
   * <code>optional uint32 all_time_low = 9;</code>
   */
  int getAllTimeLow();

  /**
   * <code>optional uint32 stocks_in_exchange = 10;</code>
   */
  int getStocksInExchange();

  /**
   * <code>optional uint32 stocks_in_market = 11;</code>
   */
  int getStocksInMarket();

  /**
   * <code>optional bool up_or_down = 12;</code>
   */
  boolean getUpOrDown();

  /**
   * <code>optional uint32 previous_day_close = 13;</code>
   */
  int getPreviousDayClose();

  /**
   * <code>optional uint32 avg_last_price = 14;</code>
   */
  int getAvgLastPrice();

  /**
   * <code>optional string created_at = 15;</code>
   */
  String getCreatedAt();
  /**
   * <code>optional string created_at = 15;</code>
   */
  com.google.protobuf.ByteString
      getCreatedAtBytes();

  /**
   * <code>optional string updated_at = 16;</code>
   */
  String getUpdatedAt();
  /**
   * <code>optional string updated_at = 16;</code>
   */
  com.google.protobuf.ByteString
      getUpdatedAtBytes();
}
