// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: models/Stock.proto

package dalalstreet.api.models;

public final class StockOuterClass {
  private StockOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
