// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: models/StockHistory.proto

package dalalstreet.api.models;

public interface StockHistoryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.StockHistory)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional uint32 stock_id = 1;</code>
   */
  int getStockId();

  /**
   * <code>optional uint32 stock_price = 2;</code>
   */
  int getStockPrice();

  /**
   * <code>optional string created_at = 3;</code>
   */
  String getCreatedAt();
  /**
   * <code>optional string created_at = 3;</code>
   */
  com.google.protobuf.ByteString
      getCreatedAtBytes();
}
