// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: models/User.proto

package dalalstreet.api.models;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.User)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional uint32 id = 1;</code>
   */
  int getId();

  /**
   * <code>optional string email = 2;</code>
   */
  String getEmail();
  /**
   * <code>optional string email = 2;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>optional string name = 3;</code>
   */
  String getName();
  /**
   * <code>optional string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional uint32 cash = 4;</code>
   */
  int getCash();

  /**
   * <code>optional int32 total = 5;</code>
   */
  int getTotal();

  /**
   * <code>optional string created_at = 6;</code>
   */
  String getCreatedAt();
  /**
   * <code>optional string created_at = 6;</code>
   */
  com.google.protobuf.ByteString
      getCreatedAtBytes();
}
