// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actions/BuyStocksFromExchange.proto

package dalalstreet.api.actions;

public interface BuyStocksFromExchangeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.BuyStocksFromExchangeRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional uint32 stock_id = 1;</code>
   */
  int getStockId();

  /**
   * <code>optional uint32 stock_quantity = 2;</code>
   */
  int getStockQuantity();
}
