// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actions/BuyStocksFromExchange.proto

package dalalstreet.api.actions;

public final class BuyStocksFromExchange {
  private BuyStocksFromExchange() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
