// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actions/CancelOrder.proto

package dalalstreet.api.actions;

public interface CancelOrderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.CancelOrderResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .proto.CancelOrderResponse.StatusCode status_code = 1;</code>
   */
  int getStatusCodeValue();
  /**
   * <code>optional .proto.CancelOrderResponse.StatusCode status_code = 1;</code>
   */
  CancelOrderResponse.StatusCode getStatusCode();

  /**
   * <code>optional string status_message = 2;</code>
   */
  String getStatusMessage();
  /**
   * <code>optional string status_message = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusMessageBytes();
}
