// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actions/CancelOrder.proto

package dalalstreet.api.actions;

public interface CancelOrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.CancelOrderRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional uint32 order_id = 1;</code>
   */
  int getOrderId();

  /**
   * <code>optional bool is_ask = 2;</code>
   */
  boolean getIsAsk();
}
