// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actions/CancelOrder.proto

package dalalstreet.api.actions;

public final class CancelOrder {
  private CancelOrder() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
