// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actions/GetCompanyProfile.proto

package dalalstreet.api.actions;

import dalalstreet.api.models.Stock;
import dalalstreet.api.models.StockHistory;

/**
 * Protobuf type {@code proto.GetCompanyProfileResponse}
 */
public  final class GetCompanyProfileResponse extends
    com.google.protobuf.GeneratedMessageLite<
            GetCompanyProfileResponse, GetCompanyProfileResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:proto.GetCompanyProfileResponse)
        GetCompanyProfileResponseOrBuilder {
  private GetCompanyProfileResponse() {
    statusMessage_ = "";
  }
  /**
   * Protobuf enum {@code proto.GetCompanyProfileResponse.StatusCode}
   */
  public enum StatusCode
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>OK = 0;</code>
     */
    OK(0),
    /**
     * <code>InternalServerError = 1;</code>
     */
    InternalServerError(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>OK = 0;</code>
     */
    public static final int OK_VALUE = 0;
    /**
     * <code>InternalServerError = 1;</code>
     */
    public static final int InternalServerError_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static StatusCode valueOf(int value) {
      return forNumber(value);
    }

    public static StatusCode forNumber(int value) {
      switch (value) {
        case 0: return OK;
        case 1: return InternalServerError;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<StatusCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        StatusCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<StatusCode>() {
            public StatusCode findValueByNumber(int number) {
              return StatusCode.forNumber(number);
            }
          };

    private final int value;

    private StatusCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.GetCompanyProfileResponse.StatusCode)
  }

  private int bitField0_;
  public static final int STATUS_CODE_FIELD_NUMBER = 1;
  private int statusCode_;
  /**
   * <code>optional .proto.GetCompanyProfileResponse.StatusCode status_code = 1;</code>
   */
  public int getStatusCodeValue() {
    return statusCode_;
  }
  /**
   * <code>optional .proto.GetCompanyProfileResponse.StatusCode status_code = 1;</code>
   */
  public GetCompanyProfileResponse.StatusCode getStatusCode() {
    GetCompanyProfileResponse.StatusCode result = GetCompanyProfileResponse.StatusCode.forNumber(statusCode_);
    return result == null ? GetCompanyProfileResponse.StatusCode.UNRECOGNIZED : result;
  }
  /**
   * <code>optional .proto.GetCompanyProfileResponse.StatusCode status_code = 1;</code>
   */
  private void setStatusCodeValue(int value) {
      statusCode_ = value;
  }
  /**
   * <code>optional .proto.GetCompanyProfileResponse.StatusCode status_code = 1;</code>
   */
  private void setStatusCode(GetCompanyProfileResponse.StatusCode value) {
    if (value == null) {
      throw new NullPointerException();
    }

    statusCode_ = value.getNumber();
  }
  /**
   * <code>optional .proto.GetCompanyProfileResponse.StatusCode status_code = 1;</code>
   */
  private void clearStatusCode() {

    statusCode_ = 0;
  }

  public static final int STATUS_MESSAGE_FIELD_NUMBER = 2;
  private String statusMessage_;
  /**
   * <code>optional string status_message = 2;</code>
   */
  public String getStatusMessage() {
    return statusMessage_;
  }
  /**
   * <code>optional string status_message = 2;</code>
   */
  public com.google.protobuf.ByteString
      getStatusMessageBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(statusMessage_);
  }
  /**
   * <code>optional string status_message = 2;</code>
   */
  private void setStatusMessage(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }

    statusMessage_ = value;
  }
  /**
   * <code>optional string status_message = 2;</code>
   */
  private void clearStatusMessage() {

    statusMessage_ = getDefaultInstance().getStatusMessage();
  }
  /**
   * <code>optional string status_message = 2;</code>
   */
  private void setStatusMessageBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

    statusMessage_ = value.toStringUtf8();
  }

  public static final int STOCK_DETAILS_FIELD_NUMBER = 3;
  private Stock stockDetails_;
  /**
   * <code>optional .proto.Stock stock_details = 3;</code>
   */
  public boolean hasStockDetails() {
    return stockDetails_ != null;
  }
  /**
   * <code>optional .proto.Stock stock_details = 3;</code>
   */
  public Stock getStockDetails() {
    return stockDetails_ == null ? Stock.getDefaultInstance() : stockDetails_;
  }
  /**
   * <code>optional .proto.Stock stock_details = 3;</code>
   */
  private void setStockDetails(Stock value) {
    if (value == null) {
      throw new NullPointerException();
    }
    stockDetails_ = value;

    }
  /**
   * <code>optional .proto.Stock stock_details = 3;</code>
   */
  private void setStockDetails(
      Stock.Builder builderForValue) {
    stockDetails_ = builderForValue.build();

  }
  /**
   * <code>optional .proto.Stock stock_details = 3;</code>
   */
  private void mergeStockDetails(Stock value) {
    if (stockDetails_ != null &&
        stockDetails_ != Stock.getDefaultInstance()) {
      stockDetails_ =
        Stock.newBuilder(stockDetails_).mergeFrom(value).buildPartial();
    } else {
      stockDetails_ = value;
    }

  }
  /**
   * <code>optional .proto.Stock stock_details = 3;</code>
   */
  private void clearStockDetails() {  stockDetails_ = null;

  }

  public static final int STOCK_HISTORY_MAP_FIELD_NUMBER = 4;
  private static final class StockHistoryMapDefaultEntryHolder {
    static final com.google.protobuf.MapEntryLite<
        String, StockHistory> defaultEntry =
            com.google.protobuf.MapEntryLite
            .<String, StockHistory>newDefaultInstance(
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                StockHistory.getDefaultInstance());
  }
  private com.google.protobuf.MapFieldLite<
      String, StockHistory> stockHistoryMap_ =
          com.google.protobuf.MapFieldLite.emptyMapField();
  private com.google.protobuf.MapFieldLite<String, StockHistory>
  internalGetStockHistoryMap() {
    return stockHistoryMap_;
  }
  private com.google.protobuf.MapFieldLite<String, StockHistory>
  internalGetMutableStockHistoryMap() {
    if (!stockHistoryMap_.isMutable()) {
      stockHistoryMap_ = stockHistoryMap_.mutableCopy();
    }
    return stockHistoryMap_;
  }

  public int getStockHistoryMapCount() {
    return internalGetStockHistoryMap().size();
  }
  /**
   * <code>map&lt;string, .proto.StockHistory&gt; stock_history_map = 4;</code>
   */

  public boolean containsStockHistoryMap(
      String key) {
    if (key == null) { throw new NullPointerException(); }
    return internalGetStockHistoryMap().containsKey(key);
  }
  /**
   * Use {@link #getStockHistoryMapMap()} instead.
   */
  @Deprecated
  public java.util.Map<String, StockHistory> getStockHistoryMap() {
    return getStockHistoryMapMap();
  }
  /**
   * <code>map&lt;string, .proto.StockHistory&gt; stock_history_map = 4;</code>
   */

  public java.util.Map<String, StockHistory> getStockHistoryMapMap() {
    return java.util.Collections.unmodifiableMap(
        internalGetStockHistoryMap());
  }
  /**
   * <code>map&lt;string, .proto.StockHistory&gt; stock_history_map = 4;</code>
   */

  public StockHistory getStockHistoryMapOrDefault(
      String key,
      StockHistory defaultValue) {
    if (key == null) { throw new NullPointerException(); }
    java.util.Map<String, StockHistory> map =
        internalGetStockHistoryMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, .proto.StockHistory&gt; stock_history_map = 4;</code>
   */

  public StockHistory getStockHistoryMapOrThrow(
      String key) {
    if (key == null) { throw new NullPointerException(); }
    java.util.Map<String, StockHistory> map =
        internalGetStockHistoryMap();
    if (!map.containsKey(key)) {
      throw new IllegalArgumentException();
    }
    return map.get(key);
  }
  /**
   * <code>map&lt;string, .proto.StockHistory&gt; stock_history_map = 4;</code>
   */
  private java.util.Map<String, StockHistory>
  getMutableStockHistoryMapMap() {
    return internalGetMutableStockHistoryMap();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (statusCode_ != GetCompanyProfileResponse.StatusCode.OK.getNumber()) {
      output.writeEnum(1, statusCode_);
    }
    if (!statusMessage_.isEmpty()) {
      output.writeString(2, getStatusMessage());
    }
    if (stockDetails_ != null) {
      output.writeMessage(3, getStockDetails());
    }
    for (java.util.Map.Entry<String, StockHistory> entry
         : internalGetStockHistoryMap().entrySet()) {
      StockHistoryMapDefaultEntryHolder.defaultEntry.serializeTo(
          output, 4, entry.getKey(), entry.getValue());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (statusCode_ != GetCompanyProfileResponse.StatusCode.OK.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, statusCode_);
    }
    if (!statusMessage_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(2, getStatusMessage());
    }
    if (stockDetails_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getStockDetails());
    }
    for (java.util.Map.Entry<String, StockHistory> entry
         : internalGetStockHistoryMap().entrySet()) {
      size += StockHistoryMapDefaultEntryHolder.defaultEntry.computeMessageSize(
        4, entry.getKey(), entry.getValue());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static GetCompanyProfileResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static GetCompanyProfileResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static GetCompanyProfileResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static GetCompanyProfileResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static GetCompanyProfileResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static GetCompanyProfileResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static GetCompanyProfileResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static GetCompanyProfileResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static GetCompanyProfileResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static GetCompanyProfileResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(GetCompanyProfileResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code proto.GetCompanyProfileResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
              GetCompanyProfileResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.GetCompanyProfileResponse)
          GetCompanyProfileResponseOrBuilder {
    // Construct using dalalstreet.api.actions.GetCompanyProfileResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional .proto.GetCompanyProfileResponse.StatusCode status_code = 1;</code>
     */
    public int getStatusCodeValue() {
      return instance.getStatusCodeValue();
    }
    /**
     * <code>optional .proto.GetCompanyProfileResponse.StatusCode status_code = 1;</code>
     */
    public Builder setStatusCodeValue(int value) {
      copyOnWrite();
      instance.setStatusCodeValue(value);
      return this;
    }
    /**
     * <code>optional .proto.GetCompanyProfileResponse.StatusCode status_code = 1;</code>
     */
    public GetCompanyProfileResponse.StatusCode getStatusCode() {
      return instance.getStatusCode();
    }
    /**
     * <code>optional .proto.GetCompanyProfileResponse.StatusCode status_code = 1;</code>
     */
    public Builder setStatusCode(GetCompanyProfileResponse.StatusCode value) {
      copyOnWrite();
      instance.setStatusCode(value);
      return this;
    }
    /**
     * <code>optional .proto.GetCompanyProfileResponse.StatusCode status_code = 1;</code>
     */
    public Builder clearStatusCode() {
      copyOnWrite();
      instance.clearStatusCode();
      return this;
    }

    /**
     * <code>optional string status_message = 2;</code>
     */
    public String getStatusMessage() {
      return instance.getStatusMessage();
    }
    /**
     * <code>optional string status_message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStatusMessageBytes() {
      return instance.getStatusMessageBytes();
    }
    /**
     * <code>optional string status_message = 2;</code>
     */
    public Builder setStatusMessage(
        String value) {
      copyOnWrite();
      instance.setStatusMessage(value);
      return this;
    }
    /**
     * <code>optional string status_message = 2;</code>
     */
    public Builder clearStatusMessage() {
      copyOnWrite();
      instance.clearStatusMessage();
      return this;
    }
    /**
     * <code>optional string status_message = 2;</code>
     */
    public Builder setStatusMessageBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setStatusMessageBytes(value);
      return this;
    }

    /**
     * <code>optional .proto.Stock stock_details = 3;</code>
     */
    public boolean hasStockDetails() {
      return instance.hasStockDetails();
    }
    /**
     * <code>optional .proto.Stock stock_details = 3;</code>
     */
    public Stock getStockDetails() {
      return instance.getStockDetails();
    }
    /**
     * <code>optional .proto.Stock stock_details = 3;</code>
     */
    public Builder setStockDetails(Stock value) {
      copyOnWrite();
      instance.setStockDetails(value);
      return this;
      }
    /**
     * <code>optional .proto.Stock stock_details = 3;</code>
     */
    public Builder setStockDetails(
        Stock.Builder builderForValue) {
      copyOnWrite();
      instance.setStockDetails(builderForValue);
      return this;
    }
    /**
     * <code>optional .proto.Stock stock_details = 3;</code>
     */
    public Builder mergeStockDetails(Stock value) {
      copyOnWrite();
      instance.mergeStockDetails(value);
      return this;
    }
    /**
     * <code>optional .proto.Stock stock_details = 3;</code>
     */
    public Builder clearStockDetails() {  copyOnWrite();
      instance.clearStockDetails();
      return this;
    }


    public int getStockHistoryMapCount() {
      return instance.getStockHistoryMapMap().size();
    }
    /**
     * <code>map&lt;string, .proto.StockHistory&gt; stock_history_map = 4;</code>
     */

    public boolean containsStockHistoryMap(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return instance.getStockHistoryMapMap().containsKey(key);
    }

    public Builder clearStockHistoryMap() {
      copyOnWrite();
      instance.getMutableStockHistoryMapMap().clear();
      return this;
    }
    /**
     * <code>map&lt;string, .proto.StockHistory&gt; stock_history_map = 4;</code>
     */

    public Builder removeStockHistoryMap(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      copyOnWrite();
      instance.getMutableStockHistoryMapMap().remove(key);
      return this;
    }
    /**
     * Use {@link #getStockHistoryMapMap()} instead.
     */
    @Deprecated
    public java.util.Map<String, StockHistory> getStockHistoryMap() {
      return getStockHistoryMapMap();
    }
    /**
     * <code>map&lt;string, .proto.StockHistory&gt; stock_history_map = 4;</code>
     */
    public java.util.Map<String, StockHistory> getStockHistoryMapMap() {
      return java.util.Collections.unmodifiableMap(
          instance.getStockHistoryMapMap());
    }
    /**
     * <code>map&lt;string, .proto.StockHistory&gt; stock_history_map = 4;</code>
     */

    public StockHistory getStockHistoryMapOrDefault(
        String key,
        StockHistory defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, StockHistory> map =
          instance.getStockHistoryMapMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .proto.StockHistory&gt; stock_history_map = 4;</code>
     */

    public StockHistory getStockHistoryMapOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, StockHistory> map =
          instance.getStockHistoryMapMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <code>map&lt;string, .proto.StockHistory&gt; stock_history_map = 4;</code>
     */
    public Builder putStockHistoryMap(
        String key,
        StockHistory value) {
      if (key == null) { throw new NullPointerException(); }
      if (value == null) { throw new NullPointerException(); }
      copyOnWrite();
      instance.getMutableStockHistoryMapMap().put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, .proto.StockHistory&gt; stock_history_map = 4;</code>
     */
    public Builder putAllStockHistoryMap(
        java.util.Map<String, StockHistory> values) {
      copyOnWrite();
      instance.getMutableStockHistoryMapMap().putAll(values);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:proto.GetCompanyProfileResponse)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new GetCompanyProfileResponse();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        stockHistoryMap_.makeImmutable();
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        GetCompanyProfileResponse other = (GetCompanyProfileResponse) arg1;
        statusCode_ = visitor.visitInt(statusCode_ != 0, statusCode_,    other.statusCode_ != 0, other.statusCode_);
        statusMessage_ = visitor.visitString(!statusMessage_.isEmpty(), statusMessage_,
            !other.statusMessage_.isEmpty(), other.statusMessage_);
        stockDetails_ = visitor.visitMessage(stockDetails_, other.stockDetails_);
        stockHistoryMap_ = visitor.visitMap(
            stockHistoryMap_, other.internalGetStockHistoryMap());
        if (visitor == MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();

                statusCode_ = rawValue;
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                statusMessage_ = s;
                break;
              }
              case 26: {
                Stock.Builder subBuilder = null;
                if (stockDetails_ != null) {
                  subBuilder = stockDetails_.toBuilder();
                }
                stockDetails_ = input.readMessage(Stock.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(stockDetails_);
                  stockDetails_ = subBuilder.buildPartial();
                }

                break;
              }
              case 34: {
                if (!stockHistoryMap_.isMutable()) {
                  stockHistoryMap_ = stockHistoryMap_.mutableCopy();
                }
                StockHistoryMapDefaultEntryHolder.defaultEntry.parseInto(stockHistoryMap_, input, extensionRegistry);  break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (GetCompanyProfileResponse.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:proto.GetCompanyProfileResponse)
  private static final GetCompanyProfileResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new GetCompanyProfileResponse();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static GetCompanyProfileResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<GetCompanyProfileResponse> PARSER;

  public static com.google.protobuf.Parser<GetCompanyProfileResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

