// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actions/GetCompanyProfile.proto

package dalalstreet.api.actions;

/**
 * Protobuf type {@code proto.GetCompanyProfileRequest}
 */
public  final class GetCompanyProfileRequest extends
    com.google.protobuf.GeneratedMessageLite<
            GetCompanyProfileRequest, GetCompanyProfileRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:proto.GetCompanyProfileRequest)
        GetCompanyProfileRequestOrBuilder {
  private GetCompanyProfileRequest() {
  }
  public static final int STOCK_ID_FIELD_NUMBER = 1;
  private int stockId_;
  /**
   * <code>optional uint32 stock_id = 1;</code>
   */
  public int getStockId() {
    return stockId_;
  }
  /**
   * <code>optional uint32 stock_id = 1;</code>
   */
  private void setStockId(int value) {

    stockId_ = value;
  }
  /**
   * <code>optional uint32 stock_id = 1;</code>
   */
  private void clearStockId() {

    stockId_ = 0;
  }

  public static final int GRANULARITY_FIELD_NUMBER = 2;
  private int granularity_;
  /**
   * <code>optional .proto.StockHistoryGranularity granularity = 2;</code>
   */
  public int getGranularityValue() {
    return granularity_;
  }
  /**
   * <code>optional .proto.StockHistoryGranularity granularity = 2;</code>
   */
  public StockHistoryGranularity getGranularity() {
    StockHistoryGranularity result = StockHistoryGranularity.forNumber(granularity_);
    return result == null ? StockHistoryGranularity.UNRECOGNIZED : result;
  }
  /**
   * <code>optional .proto.StockHistoryGranularity granularity = 2;</code>
   */
  private void setGranularityValue(int value) {
      granularity_ = value;
  }
  /**
   * <code>optional .proto.StockHistoryGranularity granularity = 2;</code>
   */
  private void setGranularity(StockHistoryGranularity value) {
    if (value == null) {
      throw new NullPointerException();
    }

    granularity_ = value.getNumber();
  }
  /**
   * <code>optional .proto.StockHistoryGranularity granularity = 2;</code>
   */
  private void clearGranularity() {

    granularity_ = 0;
  }

  public static final int GETONLYHISTORY_FIELD_NUMBER = 3;
  private boolean getOnlyHistory_;
  /**
   * <code>optional bool getOnlyHistory = 3;</code>
   */
  public boolean getGetOnlyHistory() {
    return getOnlyHistory_;
  }
  /**
   * <code>optional bool getOnlyHistory = 3;</code>
   */
  private void setGetOnlyHistory(boolean value) {

    getOnlyHistory_ = value;
  }
  /**
   * <code>optional bool getOnlyHistory = 3;</code>
   */
  private void clearGetOnlyHistory() {

    getOnlyHistory_ = false;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (stockId_ != 0) {
      output.writeUInt32(1, stockId_);
    }
    if (granularity_ != StockHistoryGranularity.OneDay.getNumber()) {
      output.writeEnum(2, granularity_);
    }
    if (getOnlyHistory_ != false) {
      output.writeBool(3, getOnlyHistory_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (stockId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, stockId_);
    }
    if (granularity_ != StockHistoryGranularity.OneDay.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, granularity_);
    }
    if (getOnlyHistory_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, getOnlyHistory_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static GetCompanyProfileRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static GetCompanyProfileRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static GetCompanyProfileRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static GetCompanyProfileRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static GetCompanyProfileRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static GetCompanyProfileRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static GetCompanyProfileRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static GetCompanyProfileRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static GetCompanyProfileRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static GetCompanyProfileRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(GetCompanyProfileRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code proto.GetCompanyProfileRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
              GetCompanyProfileRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.GetCompanyProfileRequest)
          GetCompanyProfileRequestOrBuilder {
    // Construct using dalalstreet.api.actions.GetCompanyProfileRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional uint32 stock_id = 1;</code>
     */
    public int getStockId() {
      return instance.getStockId();
    }
    /**
     * <code>optional uint32 stock_id = 1;</code>
     */
    public Builder setStockId(int value) {
      copyOnWrite();
      instance.setStockId(value);
      return this;
    }
    /**
     * <code>optional uint32 stock_id = 1;</code>
     */
    public Builder clearStockId() {
      copyOnWrite();
      instance.clearStockId();
      return this;
    }

    /**
     * <code>optional .proto.StockHistoryGranularity granularity = 2;</code>
     */
    public int getGranularityValue() {
      return instance.getGranularityValue();
    }
    /**
     * <code>optional .proto.StockHistoryGranularity granularity = 2;</code>
     */
    public Builder setGranularityValue(int value) {
      copyOnWrite();
      instance.setGranularityValue(value);
      return this;
    }
    /**
     * <code>optional .proto.StockHistoryGranularity granularity = 2;</code>
     */
    public StockHistoryGranularity getGranularity() {
      return instance.getGranularity();
    }
    /**
     * <code>optional .proto.StockHistoryGranularity granularity = 2;</code>
     */
    public Builder setGranularity(StockHistoryGranularity value) {
      copyOnWrite();
      instance.setGranularity(value);
      return this;
    }
    /**
     * <code>optional .proto.StockHistoryGranularity granularity = 2;</code>
     */
    public Builder clearGranularity() {
      copyOnWrite();
      instance.clearGranularity();
      return this;
    }

    /**
     * <code>optional bool getOnlyHistory = 3;</code>
     */
    public boolean getGetOnlyHistory() {
      return instance.getGetOnlyHistory();
    }
    /**
     * <code>optional bool getOnlyHistory = 3;</code>
     */
    public Builder setGetOnlyHistory(boolean value) {
      copyOnWrite();
      instance.setGetOnlyHistory(value);
      return this;
    }
    /**
     * <code>optional bool getOnlyHistory = 3;</code>
     */
    public Builder clearGetOnlyHistory() {
      copyOnWrite();
      instance.clearGetOnlyHistory();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:proto.GetCompanyProfileRequest)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new GetCompanyProfileRequest();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        GetCompanyProfileRequest other = (GetCompanyProfileRequest) arg1;
        stockId_ = visitor.visitInt(stockId_ != 0, stockId_,
            other.stockId_ != 0, other.stockId_);
        granularity_ = visitor.visitInt(granularity_ != 0, granularity_,    other.granularity_ != 0, other.granularity_);
        getOnlyHistory_ = visitor.visitBoolean(getOnlyHistory_ != false, getOnlyHistory_,
            other.getOnlyHistory_ != false, other.getOnlyHistory_);
        if (visitor == MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                stockId_ = input.readUInt32();
                break;
              }
              case 16: {
                int rawValue = input.readEnum();

                granularity_ = rawValue;
                break;
              }
              case 24: {

                getOnlyHistory_ = input.readBool();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (GetCompanyProfileRequest.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:proto.GetCompanyProfileRequest)
  private static final GetCompanyProfileRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new GetCompanyProfileRequest();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static GetCompanyProfileRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<GetCompanyProfileRequest> PARSER;

  public static com.google.protobuf.Parser<GetCompanyProfileRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

