// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actions/GetLeaderboard.proto

package dalalstreet.api.actions;

import dalalstreet.api.models.LeaderboardRow;
import dalalstreet.api.models.LeaderboardRowOrBuilder;

/**
 * Protobuf type {@code proto.GetLeaderboardResponse}
 */
public  final class GetLeaderboardResponse extends
    com.google.protobuf.GeneratedMessageLite<
            GetLeaderboardResponse, GetLeaderboardResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:proto.GetLeaderboardResponse)
        GetLeaderboardResponseOrBuilder {
  private GetLeaderboardResponse() {
    statusMessage_ = "";
    rankList_ = emptyProtobufList();
  }
  /**
   * Protobuf enum {@code proto.GetLeaderboardResponse.StatusCode}
   */
  public enum StatusCode
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>OK = 0;</code>
     */
    OK(0),
    /**
     * <code>InternalServerError = 1;</code>
     */
    InternalServerError(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>OK = 0;</code>
     */
    public static final int OK_VALUE = 0;
    /**
     * <code>InternalServerError = 1;</code>
     */
    public static final int InternalServerError_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static StatusCode valueOf(int value) {
      return forNumber(value);
    }

    public static StatusCode forNumber(int value) {
      switch (value) {
        case 0: return OK;
        case 1: return InternalServerError;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<StatusCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        StatusCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<StatusCode>() {
            public StatusCode findValueByNumber(int number) {
              return StatusCode.forNumber(number);
            }
          };

    private final int value;

    private StatusCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.GetLeaderboardResponse.StatusCode)
  }

  private int bitField0_;
  public static final int STATUS_CODE_FIELD_NUMBER = 1;
  private int statusCode_;
  /**
   * <code>optional .proto.GetLeaderboardResponse.StatusCode status_code = 1;</code>
   */
  public int getStatusCodeValue() {
    return statusCode_;
  }
  /**
   * <code>optional .proto.GetLeaderboardResponse.StatusCode status_code = 1;</code>
   */
  public GetLeaderboardResponse.StatusCode getStatusCode() {
    GetLeaderboardResponse.StatusCode result = GetLeaderboardResponse.StatusCode.forNumber(statusCode_);
    return result == null ? GetLeaderboardResponse.StatusCode.UNRECOGNIZED : result;
  }
  /**
   * <code>optional .proto.GetLeaderboardResponse.StatusCode status_code = 1;</code>
   */
  private void setStatusCodeValue(int value) {
      statusCode_ = value;
  }
  /**
   * <code>optional .proto.GetLeaderboardResponse.StatusCode status_code = 1;</code>
   */
  private void setStatusCode(GetLeaderboardResponse.StatusCode value) {
    if (value == null) {
      throw new NullPointerException();
    }

    statusCode_ = value.getNumber();
  }
  /**
   * <code>optional .proto.GetLeaderboardResponse.StatusCode status_code = 1;</code>
   */
  private void clearStatusCode() {

    statusCode_ = 0;
  }

  public static final int STATUS_MESSAGE_FIELD_NUMBER = 2;
  private String statusMessage_;
  /**
   * <code>optional string status_message = 2;</code>
   */
  public String getStatusMessage() {
    return statusMessage_;
  }
  /**
   * <code>optional string status_message = 2;</code>
   */
  public com.google.protobuf.ByteString
      getStatusMessageBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(statusMessage_);
  }
  /**
   * <code>optional string status_message = 2;</code>
   */
  private void setStatusMessage(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }

    statusMessage_ = value;
  }
  /**
   * <code>optional string status_message = 2;</code>
   */
  private void clearStatusMessage() {

    statusMessage_ = getDefaultInstance().getStatusMessage();
  }
  /**
   * <code>optional string status_message = 2;</code>
   */
  private void setStatusMessageBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

    statusMessage_ = value.toStringUtf8();
  }

  public static final int MY_RANK_FIELD_NUMBER = 3;
  private int myRank_;
  /**
   * <code>optional uint32 my_rank = 3;</code>
   */
  public int getMyRank() {
    return myRank_;
  }
  /**
   * <code>optional uint32 my_rank = 3;</code>
   */
  private void setMyRank(int value) {

    myRank_ = value;
  }
  /**
   * <code>optional uint32 my_rank = 3;</code>
   */
  private void clearMyRank() {

    myRank_ = 0;
  }

  public static final int TOTAL_USERS_FIELD_NUMBER = 4;
  private int totalUsers_;
  /**
   * <code>optional uint32 total_users = 4;</code>
   */
  public int getTotalUsers() {
    return totalUsers_;
  }
  /**
   * <code>optional uint32 total_users = 4;</code>
   */
  private void setTotalUsers(int value) {

    totalUsers_ = value;
  }
  /**
   * <code>optional uint32 total_users = 4;</code>
   */
  private void clearTotalUsers() {

    totalUsers_ = 0;
  }

  public static final int RANK_LIST_FIELD_NUMBER = 5;
  private com.google.protobuf.Internal.ProtobufList<LeaderboardRow> rankList_;
  /**
   * <pre>
   * key: rank, value: leaderboard row
   * </pre>
   *
   * <code>repeated .proto.LeaderboardRow rank_list = 5;</code>
   */
  public java.util.List<LeaderboardRow> getRankListList() {
    return rankList_;
  }
  /**
   * <pre>
   * key: rank, value: leaderboard row
   * </pre>
   *
   * <code>repeated .proto.LeaderboardRow rank_list = 5;</code>
   */
  public java.util.List<? extends LeaderboardRowOrBuilder>
      getRankListOrBuilderList() {
    return rankList_;
  }
  /**
   * <pre>
   * key: rank, value: leaderboard row
   * </pre>
   *
   * <code>repeated .proto.LeaderboardRow rank_list = 5;</code>
   */
  public int getRankListCount() {
    return rankList_.size();
  }
  /**
   * <pre>
   * key: rank, value: leaderboard row
   * </pre>
   *
   * <code>repeated .proto.LeaderboardRow rank_list = 5;</code>
   */
  public LeaderboardRow getRankList(int index) {
    return rankList_.get(index);
  }
  /**
   * <pre>
   * key: rank, value: leaderboard row
   * </pre>
   *
   * <code>repeated .proto.LeaderboardRow rank_list = 5;</code>
   */
  public LeaderboardRowOrBuilder getRankListOrBuilder(
      int index) {
    return rankList_.get(index);
  }
  private void ensureRankListIsMutable() {
    if (!rankList_.isModifiable()) {
      rankList_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(rankList_);
     }
  }

  /**
   * <pre>
   * key: rank, value: leaderboard row
   * </pre>
   *
   * <code>repeated .proto.LeaderboardRow rank_list = 5;</code>
   */
  private void setRankList(
      int index, LeaderboardRow value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureRankListIsMutable();
    rankList_.set(index, value);
  }
  /**
   * <pre>
   * key: rank, value: leaderboard row
   * </pre>
   *
   * <code>repeated .proto.LeaderboardRow rank_list = 5;</code>
   */
  private void setRankList(
      int index, LeaderboardRow.Builder builderForValue) {
    ensureRankListIsMutable();
    rankList_.set(index, builderForValue.build());
  }
  /**
   * <pre>
   * key: rank, value: leaderboard row
   * </pre>
   *
   * <code>repeated .proto.LeaderboardRow rank_list = 5;</code>
   */
  private void addRankList(LeaderboardRow value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureRankListIsMutable();
    rankList_.add(value);
  }
  /**
   * <pre>
   * key: rank, value: leaderboard row
   * </pre>
   *
   * <code>repeated .proto.LeaderboardRow rank_list = 5;</code>
   */
  private void addRankList(
      int index, LeaderboardRow value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureRankListIsMutable();
    rankList_.add(index, value);
  }
  /**
   * <pre>
   * key: rank, value: leaderboard row
   * </pre>
   *
   * <code>repeated .proto.LeaderboardRow rank_list = 5;</code>
   */
  private void addRankList(
      LeaderboardRow.Builder builderForValue) {
    ensureRankListIsMutable();
    rankList_.add(builderForValue.build());
  }
  /**
   * <pre>
   * key: rank, value: leaderboard row
   * </pre>
   *
   * <code>repeated .proto.LeaderboardRow rank_list = 5;</code>
   */
  private void addRankList(
      int index, LeaderboardRow.Builder builderForValue) {
    ensureRankListIsMutable();
    rankList_.add(index, builderForValue.build());
  }
  /**
   * <pre>
   * key: rank, value: leaderboard row
   * </pre>
   *
   * <code>repeated .proto.LeaderboardRow rank_list = 5;</code>
   */
  private void addAllRankList(
      Iterable<? extends LeaderboardRow> values) {
    ensureRankListIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, rankList_);
  }
  /**
   * <pre>
   * key: rank, value: leaderboard row
   * </pre>
   *
   * <code>repeated .proto.LeaderboardRow rank_list = 5;</code>
   */
  private void clearRankList() {
    rankList_ = emptyProtobufList();
  }
  /**
   * <pre>
   * key: rank, value: leaderboard row
   * </pre>
   *
   * <code>repeated .proto.LeaderboardRow rank_list = 5;</code>
   */
  private void removeRankList(int index) {
    ensureRankListIsMutable();
    rankList_.remove(index);
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (statusCode_ != GetLeaderboardResponse.StatusCode.OK.getNumber()) {
      output.writeEnum(1, statusCode_);
    }
    if (!statusMessage_.isEmpty()) {
      output.writeString(2, getStatusMessage());
    }
    if (myRank_ != 0) {
      output.writeUInt32(3, myRank_);
    }
    if (totalUsers_ != 0) {
      output.writeUInt32(4, totalUsers_);
    }
    for (int i = 0; i < rankList_.size(); i++) {
      output.writeMessage(5, rankList_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (statusCode_ != GetLeaderboardResponse.StatusCode.OK.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, statusCode_);
    }
    if (!statusMessage_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(2, getStatusMessage());
    }
    if (myRank_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, myRank_);
    }
    if (totalUsers_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, totalUsers_);
    }
    for (int i = 0; i < rankList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, rankList_.get(i));
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static GetLeaderboardResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static GetLeaderboardResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static GetLeaderboardResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static GetLeaderboardResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static GetLeaderboardResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static GetLeaderboardResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static GetLeaderboardResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static GetLeaderboardResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static GetLeaderboardResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static GetLeaderboardResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(GetLeaderboardResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code proto.GetLeaderboardResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
              GetLeaderboardResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.GetLeaderboardResponse)
          GetLeaderboardResponseOrBuilder {
    // Construct using dalalstreet.api.actions.GetLeaderboardResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional .proto.GetLeaderboardResponse.StatusCode status_code = 1;</code>
     */
    public int getStatusCodeValue() {
      return instance.getStatusCodeValue();
    }
    /**
     * <code>optional .proto.GetLeaderboardResponse.StatusCode status_code = 1;</code>
     */
    public Builder setStatusCodeValue(int value) {
      copyOnWrite();
      instance.setStatusCodeValue(value);
      return this;
    }
    /**
     * <code>optional .proto.GetLeaderboardResponse.StatusCode status_code = 1;</code>
     */
    public GetLeaderboardResponse.StatusCode getStatusCode() {
      return instance.getStatusCode();
    }
    /**
     * <code>optional .proto.GetLeaderboardResponse.StatusCode status_code = 1;</code>
     */
    public Builder setStatusCode(GetLeaderboardResponse.StatusCode value) {
      copyOnWrite();
      instance.setStatusCode(value);
      return this;
    }
    /**
     * <code>optional .proto.GetLeaderboardResponse.StatusCode status_code = 1;</code>
     */
    public Builder clearStatusCode() {
      copyOnWrite();
      instance.clearStatusCode();
      return this;
    }

    /**
     * <code>optional string status_message = 2;</code>
     */
    public String getStatusMessage() {
      return instance.getStatusMessage();
    }
    /**
     * <code>optional string status_message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStatusMessageBytes() {
      return instance.getStatusMessageBytes();
    }
    /**
     * <code>optional string status_message = 2;</code>
     */
    public Builder setStatusMessage(
        String value) {
      copyOnWrite();
      instance.setStatusMessage(value);
      return this;
    }
    /**
     * <code>optional string status_message = 2;</code>
     */
    public Builder clearStatusMessage() {
      copyOnWrite();
      instance.clearStatusMessage();
      return this;
    }
    /**
     * <code>optional string status_message = 2;</code>
     */
    public Builder setStatusMessageBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setStatusMessageBytes(value);
      return this;
    }

    /**
     * <code>optional uint32 my_rank = 3;</code>
     */
    public int getMyRank() {
      return instance.getMyRank();
    }
    /**
     * <code>optional uint32 my_rank = 3;</code>
     */
    public Builder setMyRank(int value) {
      copyOnWrite();
      instance.setMyRank(value);
      return this;
    }
    /**
     * <code>optional uint32 my_rank = 3;</code>
     */
    public Builder clearMyRank() {
      copyOnWrite();
      instance.clearMyRank();
      return this;
    }

    /**
     * <code>optional uint32 total_users = 4;</code>
     */
    public int getTotalUsers() {
      return instance.getTotalUsers();
    }
    /**
     * <code>optional uint32 total_users = 4;</code>
     */
    public Builder setTotalUsers(int value) {
      copyOnWrite();
      instance.setTotalUsers(value);
      return this;
    }
    /**
     * <code>optional uint32 total_users = 4;</code>
     */
    public Builder clearTotalUsers() {
      copyOnWrite();
      instance.clearTotalUsers();
      return this;
    }

    /**
     * <pre>
     * key: rank, value: leaderboard row
     * </pre>
     *
     * <code>repeated .proto.LeaderboardRow rank_list = 5;</code>
     */
    public java.util.List<LeaderboardRow> getRankListList() {
      return java.util.Collections.unmodifiableList(
          instance.getRankListList());
    }
    /**
     * <pre>
     * key: rank, value: leaderboard row
     * </pre>
     *
     * <code>repeated .proto.LeaderboardRow rank_list = 5;</code>
     */
    public int getRankListCount() {
      return instance.getRankListCount();
    }/**
     * <pre>
     * key: rank, value: leaderboard row
     * </pre>
     *
     * <code>repeated .proto.LeaderboardRow rank_list = 5;</code>
     */
    public LeaderboardRow getRankList(int index) {
      return instance.getRankList(index);
    }
    /**
     * <pre>
     * key: rank, value: leaderboard row
     * </pre>
     *
     * <code>repeated .proto.LeaderboardRow rank_list = 5;</code>
     */
    public Builder setRankList(
        int index, LeaderboardRow value) {
      copyOnWrite();
      instance.setRankList(index, value);
      return this;
    }
    /**
     * <pre>
     * key: rank, value: leaderboard row
     * </pre>
     *
     * <code>repeated .proto.LeaderboardRow rank_list = 5;</code>
     */
    public Builder setRankList(
        int index, LeaderboardRow.Builder builderForValue) {
      copyOnWrite();
      instance.setRankList(index, builderForValue);
      return this;
    }
    /**
     * <pre>
     * key: rank, value: leaderboard row
     * </pre>
     *
     * <code>repeated .proto.LeaderboardRow rank_list = 5;</code>
     */
    public Builder addRankList(LeaderboardRow value) {
      copyOnWrite();
      instance.addRankList(value);
      return this;
    }
    /**
     * <pre>
     * key: rank, value: leaderboard row
     * </pre>
     *
     * <code>repeated .proto.LeaderboardRow rank_list = 5;</code>
     */
    public Builder addRankList(
        int index, LeaderboardRow value) {
      copyOnWrite();
      instance.addRankList(index, value);
      return this;
    }
    /**
     * <pre>
     * key: rank, value: leaderboard row
     * </pre>
     *
     * <code>repeated .proto.LeaderboardRow rank_list = 5;</code>
     */
    public Builder addRankList(
        LeaderboardRow.Builder builderForValue) {
      copyOnWrite();
      instance.addRankList(builderForValue);
      return this;
    }
    /**
     * <pre>
     * key: rank, value: leaderboard row
     * </pre>
     *
     * <code>repeated .proto.LeaderboardRow rank_list = 5;</code>
     */
    public Builder addRankList(
        int index, LeaderboardRow.Builder builderForValue) {
      copyOnWrite();
      instance.addRankList(index, builderForValue);
      return this;
    }
    /**
     * <pre>
     * key: rank, value: leaderboard row
     * </pre>
     *
     * <code>repeated .proto.LeaderboardRow rank_list = 5;</code>
     */
    public Builder addAllRankList(
        Iterable<? extends LeaderboardRow> values) {
      copyOnWrite();
      instance.addAllRankList(values);
      return this;
    }
    /**
     * <pre>
     * key: rank, value: leaderboard row
     * </pre>
     *
     * <code>repeated .proto.LeaderboardRow rank_list = 5;</code>
     */
    public Builder clearRankList() {
      copyOnWrite();
      instance.clearRankList();
      return this;
    }
    /**
     * <pre>
     * key: rank, value: leaderboard row
     * </pre>
     *
     * <code>repeated .proto.LeaderboardRow rank_list = 5;</code>
     */
    public Builder removeRankList(int index) {
      copyOnWrite();
      instance.removeRankList(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:proto.GetLeaderboardResponse)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new GetLeaderboardResponse();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        rankList_.makeImmutable();
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        GetLeaderboardResponse other = (GetLeaderboardResponse) arg1;
        statusCode_ = visitor.visitInt(statusCode_ != 0, statusCode_,    other.statusCode_ != 0, other.statusCode_);
        statusMessage_ = visitor.visitString(!statusMessage_.isEmpty(), statusMessage_,
            !other.statusMessage_.isEmpty(), other.statusMessage_);
        myRank_ = visitor.visitInt(myRank_ != 0, myRank_,
            other.myRank_ != 0, other.myRank_);
        totalUsers_ = visitor.visitInt(totalUsers_ != 0, totalUsers_,
            other.totalUsers_ != 0, other.totalUsers_);
        rankList_= visitor.visitList(rankList_, other.rankList_);
        if (visitor == MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();

                statusCode_ = rawValue;
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                statusMessage_ = s;
                break;
              }
              case 24: {

                myRank_ = input.readUInt32();
                break;
              }
              case 32: {

                totalUsers_ = input.readUInt32();
                break;
              }
              case 42: {
                if (!rankList_.isModifiable()) {
                  rankList_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(rankList_);
                }
                rankList_.add(
                    input.readMessage(LeaderboardRow.parser(), extensionRegistry));
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (GetLeaderboardResponse.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:proto.GetLeaderboardResponse)
  private static final GetLeaderboardResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new GetLeaderboardResponse();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static GetLeaderboardResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<GetLeaderboardResponse> PARSER;

  public static com.google.protobuf.Parser<GetLeaderboardResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

