// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actions/GetLeaderboard.proto

package dalalstreet.api.actions;

import dalalstreet.api.models.LeaderboardRow;

public interface GetLeaderboardResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GetLeaderboardResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .proto.GetLeaderboardResponse.StatusCode status_code = 1;</code>
   */
  int getStatusCodeValue();
  /**
   * <code>optional .proto.GetLeaderboardResponse.StatusCode status_code = 1;</code>
   */
  GetLeaderboardResponse.StatusCode getStatusCode();

  /**
   * <code>optional string status_message = 2;</code>
   */
  String getStatusMessage();
  /**
   * <code>optional string status_message = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusMessageBytes();

  /**
   * <code>optional uint32 my_rank = 3;</code>
   */
  int getMyRank();

  /**
   * <code>optional uint32 total_users = 4;</code>
   */
  int getTotalUsers();

  /**
   * <pre>
   * key: rank, value: leaderboard row
   * </pre>
   *
   * <code>repeated .proto.LeaderboardRow rank_list = 5;</code>
   */
  java.util.List<LeaderboardRow>
      getRankListList();
  /**
   * <pre>
   * key: rank, value: leaderboard row
   * </pre>
   *
   * <code>repeated .proto.LeaderboardRow rank_list = 5;</code>
   */
  LeaderboardRow getRankList(int index);
  /**
   * <pre>
   * key: rank, value: leaderboard row
   * </pre>
   *
   * <code>repeated .proto.LeaderboardRow rank_list = 5;</code>
   */
  int getRankListCount();
}
