// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actions/GetMyOrders.proto

package dalalstreet.api.actions;

public interface GetMyOpenOrdersRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GetMyOpenOrdersRequest)
    com.google.protobuf.MessageLiteOrBuilder {
}
