// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actions/GetMyOrders.proto

package dalalstreet.api.actions;

import dalalstreet.api.models.Ask;
import dalalstreet.api.models.Bid;

public interface GetMyOpenOrdersResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GetMyOpenOrdersResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .proto.GetMyOpenOrdersResponse.StatusCode status_code = 1;</code>
   */
  int getStatusCodeValue();
  /**
   * <code>optional .proto.GetMyOpenOrdersResponse.StatusCode status_code = 1;</code>
   */
  GetMyOpenOrdersResponse.StatusCode getStatusCode();

  /**
   * <code>optional string status_message = 2;</code>
   */
  String getStatusMessage();
  /**
   * <code>optional string status_message = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusMessageBytes();

  /**
   * <code>repeated .proto.Ask open_ask_orders = 3;</code>
   */
  java.util.List<Ask>
      getOpenAskOrdersList();
  /**
   * <code>repeated .proto.Ask open_ask_orders = 3;</code>
   */
  Ask getOpenAskOrders(int index);
  /**
   * <code>repeated .proto.Ask open_ask_orders = 3;</code>
   */
  int getOpenAskOrdersCount();

  /**
   * <code>repeated .proto.Bid open_bid_orders = 4;</code>
   */
  java.util.List<Bid>
      getOpenBidOrdersList();
  /**
   * <code>repeated .proto.Bid open_bid_orders = 4;</code>
   */
  Bid getOpenBidOrders(int index);
  /**
   * <code>repeated .proto.Bid open_bid_orders = 4;</code>
   */
  int getOpenBidOrdersCount();
}
