// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actions/GetMortgageDetails.proto

package dalalstreet.api.actions;

/**
 * Protobuf type {@code proto.GetMortgageDetailsResponse}
 */
public  final class GetMortgageDetailsResponse extends
    com.google.protobuf.GeneratedMessageLite<
            GetMortgageDetailsResponse, GetMortgageDetailsResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:proto.GetMortgageDetailsResponse)
        GetMortgageDetailsResponseOrBuilder {
  private GetMortgageDetailsResponse() {
    statusMessage_ = "";
  }
  /**
   * Protobuf enum {@code proto.GetMortgageDetailsResponse.StatusCode}
   */
  public enum StatusCode
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>OK = 0;</code>
     */
    OK(0),
    /**
     * <code>InternalServerError = 1;</code>
     */
    InternalServerError(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>OK = 0;</code>
     */
    public static final int OK_VALUE = 0;
    /**
     * <code>InternalServerError = 1;</code>
     */
    public static final int InternalServerError_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static StatusCode valueOf(int value) {
      return forNumber(value);
    }

    public static StatusCode forNumber(int value) {
      switch (value) {
        case 0: return OK;
        case 1: return InternalServerError;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<StatusCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        StatusCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<StatusCode>() {
            public StatusCode findValueByNumber(int number) {
              return StatusCode.forNumber(number);
            }
          };

    private final int value;

    private StatusCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.GetMortgageDetailsResponse.StatusCode)
  }

  private int bitField0_;
  public static final int STATUS_CODE_FIELD_NUMBER = 1;
  private int statusCode_;
  /**
   * <code>optional .proto.GetMortgageDetailsResponse.StatusCode status_code = 1;</code>
   */
  public int getStatusCodeValue() {
    return statusCode_;
  }
  /**
   * <code>optional .proto.GetMortgageDetailsResponse.StatusCode status_code = 1;</code>
   */
  public GetMortgageDetailsResponse.StatusCode getStatusCode() {
    GetMortgageDetailsResponse.StatusCode result = GetMortgageDetailsResponse.StatusCode.forNumber(statusCode_);
    return result == null ? GetMortgageDetailsResponse.StatusCode.UNRECOGNIZED : result;
  }
  /**
   * <code>optional .proto.GetMortgageDetailsResponse.StatusCode status_code = 1;</code>
   */
  private void setStatusCodeValue(int value) {
      statusCode_ = value;
  }
  /**
   * <code>optional .proto.GetMortgageDetailsResponse.StatusCode status_code = 1;</code>
   */
  private void setStatusCode(GetMortgageDetailsResponse.StatusCode value) {
    if (value == null) {
      throw new NullPointerException();
    }

    statusCode_ = value.getNumber();
  }
  /**
   * <code>optional .proto.GetMortgageDetailsResponse.StatusCode status_code = 1;</code>
   */
  private void clearStatusCode() {

    statusCode_ = 0;
  }

  public static final int STATUS_MESSAGE_FIELD_NUMBER = 2;
  private String statusMessage_;
  /**
   * <code>optional string status_message = 2;</code>
   */
  public String getStatusMessage() {
    return statusMessage_;
  }
  /**
   * <code>optional string status_message = 2;</code>
   */
  public com.google.protobuf.ByteString
      getStatusMessageBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(statusMessage_);
  }
  /**
   * <code>optional string status_message = 2;</code>
   */
  private void setStatusMessage(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }

    statusMessage_ = value;
  }
  /**
   * <code>optional string status_message = 2;</code>
   */
  private void clearStatusMessage() {

    statusMessage_ = getDefaultInstance().getStatusMessage();
  }
  /**
   * <code>optional string status_message = 2;</code>
   */
  private void setStatusMessageBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

    statusMessage_ = value.toStringUtf8();
  }

  public static final int MORTGAGE_MAP_FIELD_NUMBER = 3;
  private static final class MortgageMapDefaultEntryHolder {
    static final com.google.protobuf.MapEntryLite<
        Integer, Integer> defaultEntry =
            com.google.protobuf.MapEntryLite
            .<Integer, Integer>newDefaultInstance(
                com.google.protobuf.WireFormat.FieldType.UINT32,
                0,
                com.google.protobuf.WireFormat.FieldType.UINT32,
                0);
  }
  private com.google.protobuf.MapFieldLite<
      Integer, Integer> mortgageMap_ =
          com.google.protobuf.MapFieldLite.emptyMapField();
  private com.google.protobuf.MapFieldLite<Integer, Integer>
  internalGetMortgageMap() {
    return mortgageMap_;
  }
  private com.google.protobuf.MapFieldLite<Integer, Integer>
  internalGetMutableMortgageMap() {
    if (!mortgageMap_.isMutable()) {
      mortgageMap_ = mortgageMap_.mutableCopy();
    }
    return mortgageMap_;
  }

  public int getMortgageMapCount() {
    return internalGetMortgageMap().size();
  }
  /**
   * <pre>
   * This will be updated when interest-based mortgage is implemented.
   * </pre>
   *
   * <code>map&lt;uint32, uint32&gt; mortgage_map = 3;</code>
   */

  public boolean containsMortgageMap(
      int key) {

    return internalGetMortgageMap().containsKey(key);
  }
  /**
   * Use {@link #getMortgageMapMap()} instead.
   */
  @Deprecated
  public java.util.Map<Integer, Integer> getMortgageMap() {
    return getMortgageMapMap();
  }
  /**
   * <pre>
   * This will be updated when interest-based mortgage is implemented.
   * </pre>
   *
   * <code>map&lt;uint32, uint32&gt; mortgage_map = 3;</code>
   */

  public java.util.Map<Integer, Integer> getMortgageMapMap() {
    return java.util.Collections.unmodifiableMap(
        internalGetMortgageMap());
  }
  /**
   * <pre>
   * This will be updated when interest-based mortgage is implemented.
   * </pre>
   *
   * <code>map&lt;uint32, uint32&gt; mortgage_map = 3;</code>
   */

  public int getMortgageMapOrDefault(
      int key,
      int defaultValue) {

    java.util.Map<Integer, Integer> map =
        internalGetMortgageMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * This will be updated when interest-based mortgage is implemented.
   * </pre>
   *
   * <code>map&lt;uint32, uint32&gt; mortgage_map = 3;</code>
   */

  public int getMortgageMapOrThrow(
      int key) {

    java.util.Map<Integer, Integer> map =
        internalGetMortgageMap();
    if (!map.containsKey(key)) {
      throw new IllegalArgumentException();
    }
    return map.get(key);
  }
  /**
   * <pre>
   * This will be updated when interest-based mortgage is implemented.
   * </pre>
   *
   * <code>map&lt;uint32, uint32&gt; mortgage_map = 3;</code>
   */
  private java.util.Map<Integer, Integer>
  getMutableMortgageMapMap() {
    return internalGetMutableMortgageMap();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (statusCode_ != GetMortgageDetailsResponse.StatusCode.OK.getNumber()) {
      output.writeEnum(1, statusCode_);
    }
    if (!statusMessage_.isEmpty()) {
      output.writeString(2, getStatusMessage());
    }
    for (java.util.Map.Entry<Integer, Integer> entry
         : internalGetMortgageMap().entrySet()) {
      MortgageMapDefaultEntryHolder.defaultEntry.serializeTo(
          output, 3, entry.getKey(), entry.getValue());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (statusCode_ != GetMortgageDetailsResponse.StatusCode.OK.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, statusCode_);
    }
    if (!statusMessage_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(2, getStatusMessage());
    }
    for (java.util.Map.Entry<Integer, Integer> entry
         : internalGetMortgageMap().entrySet()) {
      size += MortgageMapDefaultEntryHolder.defaultEntry.computeMessageSize(
        3, entry.getKey(), entry.getValue());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static GetMortgageDetailsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static GetMortgageDetailsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static GetMortgageDetailsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static GetMortgageDetailsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static GetMortgageDetailsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static GetMortgageDetailsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static GetMortgageDetailsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static GetMortgageDetailsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static GetMortgageDetailsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static GetMortgageDetailsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(GetMortgageDetailsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code proto.GetMortgageDetailsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
              GetMortgageDetailsResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.GetMortgageDetailsResponse)
          GetMortgageDetailsResponseOrBuilder {
    // Construct using dalalstreet.api.actions.GetMortgageDetailsResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional .proto.GetMortgageDetailsResponse.StatusCode status_code = 1;</code>
     */
    public int getStatusCodeValue() {
      return instance.getStatusCodeValue();
    }
    /**
     * <code>optional .proto.GetMortgageDetailsResponse.StatusCode status_code = 1;</code>
     */
    public Builder setStatusCodeValue(int value) {
      copyOnWrite();
      instance.setStatusCodeValue(value);
      return this;
    }
    /**
     * <code>optional .proto.GetMortgageDetailsResponse.StatusCode status_code = 1;</code>
     */
    public GetMortgageDetailsResponse.StatusCode getStatusCode() {
      return instance.getStatusCode();
    }
    /**
     * <code>optional .proto.GetMortgageDetailsResponse.StatusCode status_code = 1;</code>
     */
    public Builder setStatusCode(GetMortgageDetailsResponse.StatusCode value) {
      copyOnWrite();
      instance.setStatusCode(value);
      return this;
    }
    /**
     * <code>optional .proto.GetMortgageDetailsResponse.StatusCode status_code = 1;</code>
     */
    public Builder clearStatusCode() {
      copyOnWrite();
      instance.clearStatusCode();
      return this;
    }

    /**
     * <code>optional string status_message = 2;</code>
     */
    public String getStatusMessage() {
      return instance.getStatusMessage();
    }
    /**
     * <code>optional string status_message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStatusMessageBytes() {
      return instance.getStatusMessageBytes();
    }
    /**
     * <code>optional string status_message = 2;</code>
     */
    public Builder setStatusMessage(
        String value) {
      copyOnWrite();
      instance.setStatusMessage(value);
      return this;
    }
    /**
     * <code>optional string status_message = 2;</code>
     */
    public Builder clearStatusMessage() {
      copyOnWrite();
      instance.clearStatusMessage();
      return this;
    }
    /**
     * <code>optional string status_message = 2;</code>
     */
    public Builder setStatusMessageBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setStatusMessageBytes(value);
      return this;
    }


    public int getMortgageMapCount() {
      return instance.getMortgageMapMap().size();
    }
    /**
     * <pre>
     * This will be updated when interest-based mortgage is implemented.
     * </pre>
     *
     * <code>map&lt;uint32, uint32&gt; mortgage_map = 3;</code>
     */

    public boolean containsMortgageMap(
        int key) {

      return instance.getMortgageMapMap().containsKey(key);
    }

    public Builder clearMortgageMap() {
      copyOnWrite();
      instance.getMutableMortgageMapMap().clear();
      return this;
    }
    /**
     * <pre>
     * This will be updated when interest-based mortgage is implemented.
     * </pre>
     *
     * <code>map&lt;uint32, uint32&gt; mortgage_map = 3;</code>
     */

    public Builder removeMortgageMap(
        int key) {

      copyOnWrite();
      instance.getMutableMortgageMapMap().remove(key);
      return this;
    }
    /**
     * Use {@link #getMortgageMapMap()} instead.
     */
    @Deprecated
    public java.util.Map<Integer, Integer> getMortgageMap() {
      return getMortgageMapMap();
    }
    /**
     * <pre>
     * This will be updated when interest-based mortgage is implemented.
     * </pre>
     *
     * <code>map&lt;uint32, uint32&gt; mortgage_map = 3;</code>
     */
    public java.util.Map<Integer, Integer> getMortgageMapMap() {
      return java.util.Collections.unmodifiableMap(
          instance.getMortgageMapMap());
    }
    /**
     * <pre>
     * This will be updated when interest-based mortgage is implemented.
     * </pre>
     *
     * <code>map&lt;uint32, uint32&gt; mortgage_map = 3;</code>
     */

    public int getMortgageMapOrDefault(
        int key,
        int defaultValue) {

      java.util.Map<Integer, Integer> map =
          instance.getMortgageMapMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * This will be updated when interest-based mortgage is implemented.
     * </pre>
     *
     * <code>map&lt;uint32, uint32&gt; mortgage_map = 3;</code>
     */

    public int getMortgageMapOrThrow(
        int key) {

      java.util.Map<Integer, Integer> map =
          instance.getMortgageMapMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <pre>
     * This will be updated when interest-based mortgage is implemented.
     * </pre>
     *
     * <code>map&lt;uint32, uint32&gt; mortgage_map = 3;</code>
     */
    public Builder putMortgageMap(
        int key,
        int value) {


      copyOnWrite();
      instance.getMutableMortgageMapMap().put(key, value);
      return this;
    }
    /**
     * <pre>
     * This will be updated when interest-based mortgage is implemented.
     * </pre>
     *
     * <code>map&lt;uint32, uint32&gt; mortgage_map = 3;</code>
     */
    public Builder putAllMortgageMap(
        java.util.Map<Integer, Integer> values) {
      copyOnWrite();
      instance.getMutableMortgageMapMap().putAll(values);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:proto.GetMortgageDetailsResponse)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new GetMortgageDetailsResponse();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        mortgageMap_.makeImmutable();
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        GetMortgageDetailsResponse other = (GetMortgageDetailsResponse) arg1;
        statusCode_ = visitor.visitInt(statusCode_ != 0, statusCode_,    other.statusCode_ != 0, other.statusCode_);
        statusMessage_ = visitor.visitString(!statusMessage_.isEmpty(), statusMessage_,
            !other.statusMessage_.isEmpty(), other.statusMessage_);
        mortgageMap_ = visitor.visitMap(
            mortgageMap_, other.internalGetMortgageMap());
        if (visitor == MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();

                statusCode_ = rawValue;
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                statusMessage_ = s;
                break;
              }
              case 26: {
                if (!mortgageMap_.isMutable()) {
                  mortgageMap_ = mortgageMap_.mutableCopy();
                }
                MortgageMapDefaultEntryHolder.defaultEntry.parseInto(mortgageMap_, input, extensionRegistry);  break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (GetMortgageDetailsResponse.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:proto.GetMortgageDetailsResponse)
  private static final GetMortgageDetailsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new GetMortgageDetailsResponse();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static GetMortgageDetailsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<GetMortgageDetailsResponse> PARSER;

  public static com.google.protobuf.Parser<GetMortgageDetailsResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

