// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actions/GetNotifications.proto

package dalalstreet.api.actions;

import dalalstreet.api.models.Notification;

public interface GetNotificationsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.GetNotificationsResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .proto.GetNotificationsResponse.StatusCode status_code = 1;</code>
   */
  int getStatusCodeValue();
  /**
   * <code>optional .proto.GetNotificationsResponse.StatusCode status_code = 1;</code>
   */
  GetNotificationsResponse.StatusCode getStatusCode();

  /**
   * <code>optional string status_message = 2;</code>
   */
  String getStatusMessage();
  /**
   * <code>optional string status_message = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusMessageBytes();

  /**
   * <code>optional bool more_exists = 3;</code>
   */
  boolean getMoreExists();

  /**
   * <code>repeated .proto.Notification notifications = 4;</code>
   */
  java.util.List<Notification>
      getNotificationsList();
  /**
   * <code>repeated .proto.Notification notifications = 4;</code>
   */
  Notification getNotifications(int index);
  /**
   * <code>repeated .proto.Notification notifications = 4;</code>
   */
  int getNotificationsCount();
}
