// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actions/GetTransactions.proto

package dalalstreet.api.actions;

/**
 * Protobuf type {@code proto.GetTransactionsRequest}
 */
public  final class GetTransactionsRequest extends
    com.google.protobuf.GeneratedMessageLite<
            GetTransactionsRequest, GetTransactionsRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:proto.GetTransactionsRequest)
        GetTransactionsRequestOrBuilder {
  private GetTransactionsRequest() {
  }
  public static final int LAST_TRANSACTION_ID_FIELD_NUMBER = 1;
  private int lastTransactionId_;
  /**
   * <pre>
   * 0 for latest transactions
   * </pre>
   *
   * <code>optional uint32 last_transaction_id = 1;</code>
   */
  public int getLastTransactionId() {
    return lastTransactionId_;
  }
  /**
   * <pre>
   * 0 for latest transactions
   * </pre>
   *
   * <code>optional uint32 last_transaction_id = 1;</code>
   */
  private void setLastTransactionId(int value) {

    lastTransactionId_ = value;
  }
  /**
   * <pre>
   * 0 for latest transactions
   * </pre>
   *
   * <code>optional uint32 last_transaction_id = 1;</code>
   */
  private void clearLastTransactionId() {

    lastTransactionId_ = 0;
  }

  public static final int COUNT_FIELD_NUMBER = 2;
  private int count_;
  /**
   * <pre>
   * Set to 0 for getting max transactions allowed.
   * </pre>
   *
   * <code>optional uint32 count = 2;</code>
   */
  public int getCount() {
    return count_;
  }
  /**
   * <pre>
   * Set to 0 for getting max transactions allowed.
   * </pre>
   *
   * <code>optional uint32 count = 2;</code>
   */
  private void setCount(int value) {

    count_ = value;
  }
  /**
   * <pre>
   * Set to 0 for getting max transactions allowed.
   * </pre>
   *
   * <code>optional uint32 count = 2;</code>
   */
  private void clearCount() {

    count_ = 0;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (lastTransactionId_ != 0) {
      output.writeUInt32(1, lastTransactionId_);
    }
    if (count_ != 0) {
      output.writeUInt32(2, count_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (lastTransactionId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, lastTransactionId_);
    }
    if (count_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, count_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static GetTransactionsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static GetTransactionsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static GetTransactionsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static GetTransactionsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static GetTransactionsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static GetTransactionsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static GetTransactionsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static GetTransactionsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static GetTransactionsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static GetTransactionsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(GetTransactionsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code proto.GetTransactionsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
              GetTransactionsRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.GetTransactionsRequest)
          GetTransactionsRequestOrBuilder {
    // Construct using dalalstreet.api.actions.GetTransactionsRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * 0 for latest transactions
     * </pre>
     *
     * <code>optional uint32 last_transaction_id = 1;</code>
     */
    public int getLastTransactionId() {
      return instance.getLastTransactionId();
    }
    /**
     * <pre>
     * 0 for latest transactions
     * </pre>
     *
     * <code>optional uint32 last_transaction_id = 1;</code>
     */
    public Builder setLastTransactionId(int value) {
      copyOnWrite();
      instance.setLastTransactionId(value);
      return this;
    }
    /**
     * <pre>
     * 0 for latest transactions
     * </pre>
     *
     * <code>optional uint32 last_transaction_id = 1;</code>
     */
    public Builder clearLastTransactionId() {
      copyOnWrite();
      instance.clearLastTransactionId();
      return this;
    }

    /**
     * <pre>
     * Set to 0 for getting max transactions allowed.
     * </pre>
     *
     * <code>optional uint32 count = 2;</code>
     */
    public int getCount() {
      return instance.getCount();
    }
    /**
     * <pre>
     * Set to 0 for getting max transactions allowed.
     * </pre>
     *
     * <code>optional uint32 count = 2;</code>
     */
    public Builder setCount(int value) {
      copyOnWrite();
      instance.setCount(value);
      return this;
    }
    /**
     * <pre>
     * Set to 0 for getting max transactions allowed.
     * </pre>
     *
     * <code>optional uint32 count = 2;</code>
     */
    public Builder clearCount() {
      copyOnWrite();
      instance.clearCount();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:proto.GetTransactionsRequest)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new GetTransactionsRequest();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        GetTransactionsRequest other = (GetTransactionsRequest) arg1;
        lastTransactionId_ = visitor.visitInt(lastTransactionId_ != 0, lastTransactionId_,
            other.lastTransactionId_ != 0, other.lastTransactionId_);
        count_ = visitor.visitInt(count_ != 0, count_,
            other.count_ != 0, other.count_);
        if (visitor == MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                lastTransactionId_ = input.readUInt32();
                break;
              }
              case 16: {

                count_ = input.readUInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (GetTransactionsRequest.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:proto.GetTransactionsRequest)
  private static final GetTransactionsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new GetTransactionsRequest();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static GetTransactionsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<GetTransactionsRequest> PARSER;

  public static com.google.protobuf.Parser<GetTransactionsRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

