// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actions/Login.proto

package dalalstreet.api.actions;

/**
 * Protobuf type {@code proto.LoginRequest}
 */
public  final class LoginRequest extends
    com.google.protobuf.GeneratedMessageLite<
            LoginRequest, LoginRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:proto.LoginRequest)
        LoginRequestOrBuilder {
  private LoginRequest() {
    email_ = "";
    password_ = "";
  }
  public static final int EMAIL_FIELD_NUMBER = 1;
  private String email_;
  /**
   * <code>optional string email = 1;</code>
   */
  public String getEmail() {
    return email_;
  }
  /**
   * <code>optional string email = 1;</code>
   */
  public com.google.protobuf.ByteString
      getEmailBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(email_);
  }
  /**
   * <code>optional string email = 1;</code>
   */
  private void setEmail(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }

    email_ = value;
  }
  /**
   * <code>optional string email = 1;</code>
   */
  private void clearEmail() {

    email_ = getDefaultInstance().getEmail();
  }
  /**
   * <code>optional string email = 1;</code>
   */
  private void setEmailBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

    email_ = value.toStringUtf8();
  }

  public static final int PASSWORD_FIELD_NUMBER = 2;
  private String password_;
  /**
   * <code>optional string password = 2;</code>
   */
  public String getPassword() {
    return password_;
  }
  /**
   * <code>optional string password = 2;</code>
   */
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(password_);
  }
  /**
   * <code>optional string password = 2;</code>
   */
  private void setPassword(
      String value) {
    if (value == null) {
    throw new NullPointerException();
  }

    password_ = value;
  }
  /**
   * <code>optional string password = 2;</code>
   */
  private void clearPassword() {

    password_ = getDefaultInstance().getPassword();
  }
  /**
   * <code>optional string password = 2;</code>
   */
  private void setPasswordBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

    password_ = value.toStringUtf8();
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!email_.isEmpty()) {
      output.writeString(1, getEmail());
    }
    if (!password_.isEmpty()) {
      output.writeString(2, getPassword());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!email_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getEmail());
    }
    if (!password_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(2, getPassword());
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static LoginRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static LoginRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static LoginRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static LoginRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static LoginRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static LoginRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static LoginRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static LoginRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static LoginRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static LoginRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(LoginRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code proto.LoginRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
              LoginRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.LoginRequest)
          LoginRequestOrBuilder {
    // Construct using dalalstreet.api.actions.LoginRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional string email = 1;</code>
     */
    public String getEmail() {
      return instance.getEmail();
    }
    /**
     * <code>optional string email = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      return instance.getEmailBytes();
    }
    /**
     * <code>optional string email = 1;</code>
     */
    public Builder setEmail(
        String value) {
      copyOnWrite();
      instance.setEmail(value);
      return this;
    }
    /**
     * <code>optional string email = 1;</code>
     */
    public Builder clearEmail() {
      copyOnWrite();
      instance.clearEmail();
      return this;
    }
    /**
     * <code>optional string email = 1;</code>
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setEmailBytes(value);
      return this;
    }

    /**
     * <code>optional string password = 2;</code>
     */
    public String getPassword() {
      return instance.getPassword();
    }
    /**
     * <code>optional string password = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      return instance.getPasswordBytes();
    }
    /**
     * <code>optional string password = 2;</code>
     */
    public Builder setPassword(
        String value) {
      copyOnWrite();
      instance.setPassword(value);
      return this;
    }
    /**
     * <code>optional string password = 2;</code>
     */
    public Builder clearPassword() {
      copyOnWrite();
      instance.clearPassword();
      return this;
    }
    /**
     * <code>optional string password = 2;</code>
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPasswordBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:proto.LoginRequest)
  }
  protected final Object dynamicMethod(
      MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new LoginRequest();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        LoginRequest other = (LoginRequest) arg1;
        email_ = visitor.visitString(!email_.isEmpty(), email_,
            !other.email_.isEmpty(), other.email_);
        password_ = visitor.visitString(!password_.isEmpty(), password_,
            !other.password_.isEmpty(), other.password_);
        if (visitor == MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                email_ = s;
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();

                password_ = s;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (LoginRequest.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:proto.LoginRequest)
  private static final LoginRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new LoginRequest();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static LoginRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<LoginRequest> PARSER;

  public static com.google.protobuf.Parser<LoginRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

