// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actions/Login.proto

package dalalstreet.api.actions;

import dalalstreet.api.models.Stock;
import dalalstreet.api.models.User;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.LoginResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .proto.LoginResponse.StatusCode status_code = 1;</code>
   */
  int getStatusCodeValue();
  /**
   * <code>optional .proto.LoginResponse.StatusCode status_code = 1;</code>
   */
  LoginResponse.StatusCode getStatusCode();

  /**
   * <code>optional string status_message = 2;</code>
   */
  String getStatusMessage();
  /**
   * <code>optional string status_message = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusMessageBytes();

  /**
   * <code>optional string session_id = 3;</code>
   */
  String getSessionId();
  /**
   * <code>optional string session_id = 3;</code>
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <code>optional .proto.User user = 4;</code>
   */
  boolean hasUser();
  /**
   * <code>optional .proto.User user = 4;</code>
   */
  User getUser();

  /**
   * <code>map&lt;uint32, int32&gt; stocks_owned = 5;</code>
   */
  int getStocksOwnedCount();
  /**
   * <code>map&lt;uint32, int32&gt; stocks_owned = 5;</code>
   */
  boolean containsStocksOwned(
          int key);
  /**
   * Use {@link #getStocksOwnedMap()} instead.
   */
  @Deprecated
  java.util.Map<Integer, Integer>
  getStocksOwned();
  /**
   * <code>map&lt;uint32, int32&gt; stocks_owned = 5;</code>
   */
  java.util.Map<Integer, Integer>
  getStocksOwnedMap();
  /**
   * <code>map&lt;uint32, int32&gt; stocks_owned = 5;</code>
   */

  int getStocksOwnedOrDefault(
          int key,
          int defaultValue);
  /**
   * <code>map&lt;uint32, int32&gt; stocks_owned = 5;</code>
   */

  int getStocksOwnedOrThrow(
          int key);

  /**
   * <code>map&lt;uint32, .proto.Stock&gt; stock_list = 6;</code>
   */
  int getStockListCount();
  /**
   * <code>map&lt;uint32, .proto.Stock&gt; stock_list = 6;</code>
   */
  boolean containsStockList(
          int key);
  /**
   * Use {@link #getStockListMap()} instead.
   */
  @Deprecated
  java.util.Map<Integer, Stock>
  getStockList();
  /**
   * <code>map&lt;uint32, .proto.Stock&gt; stock_list = 6;</code>
   */
  java.util.Map<Integer, Stock>
  getStockListMap();
  /**
   * <code>map&lt;uint32, .proto.Stock&gt; stock_list = 6;</code>
   */

  Stock getStockListOrDefault(
          int key,
          Stock defaultValue);
  /**
   * <code>map&lt;uint32, .proto.Stock&gt; stock_list = 6;</code>
   */

  Stock getStockListOrThrow(
          int key);

  /**
   * <code>map&lt;string, int32&gt; constants = 7;</code>
   */
  int getConstantsCount();
  /**
   * <code>map&lt;string, int32&gt; constants = 7;</code>
   */
  boolean containsConstants(
          String key);
  /**
   * Use {@link #getConstantsMap()} instead.
   */
  @Deprecated
  java.util.Map<String, Integer>
  getConstants();
  /**
   * <code>map&lt;string, int32&gt; constants = 7;</code>
   */
  java.util.Map<String, Integer>
  getConstantsMap();
  /**
   * <code>map&lt;string, int32&gt; constants = 7;</code>
   */

  int getConstantsOrDefault(
          String key,
          int defaultValue);
  /**
   * <code>map&lt;string, int32&gt; constants = 7;</code>
   */

  int getConstantsOrThrow(
          String key);

  /**
   * <code>optional string market_is_open_hacky_notif = 8;</code>
   */
  String getMarketIsOpenHackyNotif();
  /**
   * <code>optional string market_is_open_hacky_notif = 8;</code>
   */
  com.google.protobuf.ByteString
      getMarketIsOpenHackyNotifBytes();

  /**
   * <code>optional string market_is_closed_hacky_notif = 9;</code>
   */
  String getMarketIsClosedHackyNotif();
  /**
   * <code>optional string market_is_closed_hacky_notif = 9;</code>
   */
  com.google.protobuf.ByteString
      getMarketIsClosedHackyNotifBytes();

  /**
   * <code>optional bool is_market_open = 10;</code>
   */
  boolean getIsMarketOpen();
}
