// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actions/Logout.proto

package dalalstreet.api.actions;

public interface LogoutRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.LogoutRequest)
    com.google.protobuf.MessageLiteOrBuilder {
}
