// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actions/MortgageStocks.proto

package dalalstreet.api.actions;

public final class MortgageStocks {
  private MortgageStocks() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
