// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actions/MortgageStocks.proto

package dalalstreet.api.actions;

public interface MortgageStocksRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.MortgageStocksRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional uint32 stock_id = 1;</code>
   */
  int getStockId();

  /**
   * <code>optional uint32 stock_quantity = 2;</code>
   */
  int getStockQuantity();
}
