// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actions/MortgageStocks.proto

package dalalstreet.api.actions;

import dalalstreet.api.models.Transaction;

public interface MortgageStocksResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.MortgageStocksResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .proto.MortgageStocksResponse.StatusCode status_code = 1;</code>
   */
  int getStatusCodeValue();
  /**
   * <code>optional .proto.MortgageStocksResponse.StatusCode status_code = 1;</code>
   */
  MortgageStocksResponse.StatusCode getStatusCode();

  /**
   * <code>optional string status_message = 2;</code>
   */
  String getStatusMessage();
  /**
   * <code>optional string status_message = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusMessageBytes();

  /**
   * <code>optional .proto.Transaction transaction = 3;</code>
   */
  boolean hasTransaction();
  /**
   * <code>optional .proto.Transaction transaction = 3;</code>
   */
  Transaction getTransaction();
}
