// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actions/PlaceOrder.proto

package dalalstreet.api.actions;

public final class PlaceOrder {
  private PlaceOrder() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
