// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: actions/PlaceOrder.proto

package dalalstreet.api.actions;

import dalalstreet.api.models.OrderType;

public interface PlaceOrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.PlaceOrderRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional bool is_ask = 1;</code>
   */
  boolean getIsAsk();

  /**
   * <code>optional uint32 stock_id = 2;</code>
   */
  int getStockId();

  /**
   * <code>optional .proto.OrderType order_type = 3;</code>
   */
  int getOrderTypeValue();
  /**
   * <code>optional .proto.OrderType order_type = 3;</code>
   */
  OrderType getOrderType();

  /**
   * <code>optional uint32 price = 4;</code>
   */
  int getPrice();

  /**
   * <code>optional uint32 stock_quantity = 5;</code>
   */
  int getStockQuantity();
}
